; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	IID_IMetaDataImport
PUBLIC	IID_IMetaDataAssemblyImport
PUBLIC	?g_tkCorEncodeToken@@3QBIB			; g_tkCorEncodeToken
;	COMDAT ?g_tkCorEncodeToken@@3QBIB
CONST	SEGMENT
?g_tkCorEncodeToken@@3QBIB DD 02000000H			; g_tkCorEncodeToken
	DD	01000000H
	DD	01b000000H
	DD	072000000H
CONST	ENDS
;	COMDAT IID_IMetaDataAssemblyImport
CONST	SEGMENT
IID_IMetaDataAssemblyImport DD 0ee62470bH
	DW	0e94bH
	DW	0424eH
	DB	09bH
	DB	07cH
	DB	02fH
	DB	00H
	DB	0c9H
	DB	024H
	DB	09fH
	DB	093H
CONST	ENDS
;	COMDAT IID_IMetaDataImport
CONST	SEGMENT
IID_IMetaDataImport DD 07dac8207H
	DW	0d3aeH
	DW	04c75H
	DB	09bH
	DB	067H
	DB	092H
	DB	080H
	DB	01aH
	DB	049H
	DB	07dH
	DB	044H
END
