; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?HandleDestroyed@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::HandleDestroyed
PUBLIC	?HandleCreated@CCorProfilerCallbackImpl@@UEAAJ_K0@Z ; CCorProfilerCallbackImpl::HandleCreated
PUBLIC	?RootReferences2@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAW4__MIDL___MIDL_itf_corprof_0011_0001@@QEAW4__MIDL___MIDL_itf_corprof_0011_0002@@0@Z ; CCorProfilerCallbackImpl::RootReferences2
PUBLIC	?FinalizeableObjectQueued@CCorProfilerCallbackImpl@@UEAAJK_K@Z ; CCorProfilerCallbackImpl::FinalizeableObjectQueued
PUBLIC	?GarbageCollectionFinished@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::GarbageCollectionFinished
PUBLIC	?SurvivingReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAK@Z ; CCorProfilerCallbackImpl::SurvivingReferences
PUBLIC	?GarbageCollectionStarted@CCorProfilerCallbackImpl@@UEAAJHQEAHW4__MIDL___MIDL_itf_corprof_0011_0006@@@Z ; CCorProfilerCallbackImpl::GarbageCollectionStarted
PUBLIC	?ThreadNameChanged@CCorProfilerCallbackImpl@@UEAAJ_KKQEA_W@Z ; CCorProfilerCallbackImpl::ThreadNameChanged
PUBLIC	?ExceptionCLRCatcherExecute@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::ExceptionCLRCatcherExecute
PUBLIC	?ExceptionCLRCatcherFound@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::ExceptionCLRCatcherFound
PUBLIC	?COMClassicVTableDestroyed@CCorProfilerCallbackImpl@@UEAAJ_KAEBU_GUID@@PEAX@Z ; CCorProfilerCallbackImpl::COMClassicVTableDestroyed
PUBLIC	?COMClassicVTableCreated@CCorProfilerCallbackImpl@@UEAAJ_KAEBU_GUID@@PEAXK@Z ; CCorProfilerCallbackImpl::COMClassicVTableCreated
PUBLIC	?ExceptionCatcherLeave@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::ExceptionCatcherLeave
PUBLIC	?ExceptionCatcherEnter@CCorProfilerCallbackImpl@@UEAAJ_K0@Z ; CCorProfilerCallbackImpl::ExceptionCatcherEnter
PUBLIC	?ExceptionUnwindFinallyLeave@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyLeave
PUBLIC	?ExceptionUnwindFinallyEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyEnter
PUBLIC	?ExceptionUnwindFunctionLeave@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionLeave
PUBLIC	?ExceptionUnwindFunctionEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionEnter
PUBLIC	?ExceptionOSHandlerLeave@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ExceptionOSHandlerLeave
PUBLIC	?ExceptionOSHandlerEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ExceptionOSHandlerEnter
PUBLIC	?ExceptionSearchCatcherFound@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ExceptionSearchCatcherFound
PUBLIC	?ExceptionSearchFilterLeave@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::ExceptionSearchFilterLeave
PUBLIC	?ExceptionSearchFilterEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ExceptionSearchFilterEnter
PUBLIC	?ExceptionSearchFunctionLeave@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::ExceptionSearchFunctionLeave
PUBLIC	?ExceptionSearchFunctionEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ExceptionSearchFunctionEnter
PUBLIC	?ExceptionThrown@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ExceptionThrown
PUBLIC	?RootReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_K@Z ; CCorProfilerCallbackImpl::RootReferences
PUBLIC	?ObjectReferences@CCorProfilerCallbackImpl@@UEAAJ_K0KQEA_K@Z ; CCorProfilerCallbackImpl::ObjectReferences
PUBLIC	?ObjectsAllocatedByClass@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAK@Z ; CCorProfilerCallbackImpl::ObjectsAllocatedByClass
PUBLIC	?ObjectAllocated@CCorProfilerCallbackImpl@@UEAAJ_K0@Z ; CCorProfilerCallbackImpl::ObjectAllocated
PUBLIC	?MovedReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_K0QEAK@Z ; CCorProfilerCallbackImpl::MovedReferences
PUBLIC	?RuntimeThreadResumed@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::RuntimeThreadResumed
PUBLIC	?RuntimeThreadSuspended@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::RuntimeThreadSuspended
PUBLIC	?RuntimeResumeFinished@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::RuntimeResumeFinished
PUBLIC	?RuntimeResumeStarted@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::RuntimeResumeStarted
PUBLIC	?RuntimeSuspendAborted@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::RuntimeSuspendAborted
PUBLIC	?RuntimeSuspendFinished@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::RuntimeSuspendFinished
PUBLIC	?RuntimeSuspendStarted@CCorProfilerCallbackImpl@@UEAAJW4__MIDL___MIDL_itf_corprof_0000_0006@@@Z ; CCorProfilerCallbackImpl::RuntimeSuspendStarted
PUBLIC	?ManagedToUnmanagedTransition@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z ; CCorProfilerCallbackImpl::ManagedToUnmanagedTransition
PUBLIC	?UnmanagedToManagedTransition@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z ; CCorProfilerCallbackImpl::UnmanagedToManagedTransition
PUBLIC	?RemotingServerSendingReply@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z ; CCorProfilerCallbackImpl::RemotingServerSendingReply
PUBLIC	?RemotingServerInvocationReturned@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::RemotingServerInvocationReturned
PUBLIC	?RemotingServerInvocationStarted@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::RemotingServerInvocationStarted
PUBLIC	?RemotingServerReceivingMessage@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z ; CCorProfilerCallbackImpl::RemotingServerReceivingMessage
PUBLIC	?RemotingClientInvocationFinished@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::RemotingClientInvocationFinished
PUBLIC	?RemotingClientReceivingReply@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z ; CCorProfilerCallbackImpl::RemotingClientReceivingReply
PUBLIC	?RemotingClientSendingMessage@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z ; CCorProfilerCallbackImpl::RemotingClientSendingMessage
PUBLIC	?RemotingClientInvocationStarted@CCorProfilerCallbackImpl@@UEAAJXZ ; CCorProfilerCallbackImpl::RemotingClientInvocationStarted
PUBLIC	?ThreadAssignedToOSThread@CCorProfilerCallbackImpl@@UEAAJ_KK@Z ; CCorProfilerCallbackImpl::ThreadAssignedToOSThread
PUBLIC	?ThreadDestroyed@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ThreadDestroyed
PUBLIC	?ThreadCreated@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ThreadCreated
PUBLIC	?JITInlining@CCorProfilerCallbackImpl@@UEAAJ_K0PEAH@Z ; CCorProfilerCallbackImpl::JITInlining
PUBLIC	?JITFunctionPitched@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::JITFunctionPitched
PUBLIC	?JITCachedFunctionSearchFinished@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0004@@@Z ; CCorProfilerCallbackImpl::JITCachedFunctionSearchFinished
PUBLIC	?JITCachedFunctionSearchStarted@CCorProfilerCallbackImpl@@UEAAJ_KPEAH@Z ; CCorProfilerCallbackImpl::JITCachedFunctionSearchStarted
PUBLIC	?JITCompilationFinished@CCorProfilerCallbackImpl@@UEAAJ_KJH@Z ; CCorProfilerCallbackImpl::JITCompilationFinished
PUBLIC	?JITCompilationStarted@CCorProfilerCallbackImpl@@UEAAJ_KH@Z ; CCorProfilerCallbackImpl::JITCompilationStarted
PUBLIC	?FunctionUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::FunctionUnloadStarted
PUBLIC	?ClassUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ; CCorProfilerCallbackImpl::ClassUnloadFinished
PUBLIC	?ClassUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ClassUnloadStarted
PUBLIC	?ClassLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ; CCorProfilerCallbackImpl::ClassLoadFinished
PUBLIC	?ClassLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ClassLoadStarted
PUBLIC	?ModuleAttachedToAssembly@CCorProfilerCallbackImpl@@UEAAJ_K0@Z ; CCorProfilerCallbackImpl::ModuleAttachedToAssembly
PUBLIC	?ModuleUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ; CCorProfilerCallbackImpl::ModuleUnloadFinished
PUBLIC	?ModuleUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ModuleUnloadStarted
PUBLIC	?ModuleLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ; CCorProfilerCallbackImpl::ModuleLoadFinished
PUBLIC	?ModuleLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::ModuleLoadStarted
PUBLIC	?AssemblyUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ; CCorProfilerCallbackImpl::AssemblyUnloadFinished
PUBLIC	?AssemblyUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::AssemblyUnloadStarted
PUBLIC	?AssemblyLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ; CCorProfilerCallbackImpl::AssemblyLoadFinished
PUBLIC	?AssemblyLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::AssemblyLoadStarted
PUBLIC	?AppDomainShutdownFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ; CCorProfilerCallbackImpl::AppDomainShutdownFinished
PUBLIC	?AppDomainShutdownStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::AppDomainShutdownStarted
PUBLIC	?AppDomainCreationFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ; CCorProfilerCallbackImpl::AppDomainCreationFinished
PUBLIC	?AppDomainCreationStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ; CCorProfilerCallbackImpl::AppDomainCreationStarted
PUBLIC	?Shutdown@CCorProfilerCallbackImpl@@UEAAJXZ	; CCorProfilerCallbackImpl::Shutdown
PUBLIC	?Initialize@CCorProfilerCallbackImpl@@UEAAJPEAUIUnknown@@@Z ; CCorProfilerCallbackImpl::Initialize
PUBLIC	??0IUnknown@@QEAA@XZ				; IUnknown::IUnknown
PUBLIC	??0ICorProfilerCallback@@QEAA@XZ		; ICorProfilerCallback::ICorProfilerCallback
PUBLIC	??0ICorProfilerCallback2@@QEAA@XZ		; ICorProfilerCallback2::ICorProfilerCallback2
PUBLIC	??_7CCorProfilerCallbackImpl@@6B@		; CCorProfilerCallbackImpl::`vftable'
EXTRN	_purecall:PROC
;	COMDAT ??_7CCorProfilerCallbackImpl@@6B@
CONST	SEGMENT
??_7CCorProfilerCallbackImpl@@6B@ DQ FLAT:_purecall	; CCorProfilerCallbackImpl::`vftable'
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:?Initialize@CCorProfilerCallbackImpl@@UEAAJPEAUIUnknown@@@Z
	DQ	FLAT:?Shutdown@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?AppDomainCreationStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?AppDomainCreationFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
	DQ	FLAT:?AppDomainShutdownStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?AppDomainShutdownFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
	DQ	FLAT:?AssemblyLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?AssemblyLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
	DQ	FLAT:?AssemblyUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?AssemblyUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
	DQ	FLAT:?ModuleLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ModuleLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
	DQ	FLAT:?ModuleUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ModuleUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
	DQ	FLAT:?ModuleAttachedToAssembly@CCorProfilerCallbackImpl@@UEAAJ_K0@Z
	DQ	FLAT:?ClassLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ClassLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
	DQ	FLAT:?ClassUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ClassUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
	DQ	FLAT:?FunctionUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?JITCompilationStarted@CCorProfilerCallbackImpl@@UEAAJ_KH@Z
	DQ	FLAT:?JITCompilationFinished@CCorProfilerCallbackImpl@@UEAAJ_KJH@Z
	DQ	FLAT:?JITCachedFunctionSearchStarted@CCorProfilerCallbackImpl@@UEAAJ_KPEAH@Z
	DQ	FLAT:?JITCachedFunctionSearchFinished@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0004@@@Z
	DQ	FLAT:?JITFunctionPitched@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?JITInlining@CCorProfilerCallbackImpl@@UEAAJ_K0PEAH@Z
	DQ	FLAT:?ThreadCreated@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ThreadDestroyed@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ThreadAssignedToOSThread@CCorProfilerCallbackImpl@@UEAAJ_KK@Z
	DQ	FLAT:?RemotingClientInvocationStarted@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?RemotingClientSendingMessage@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z
	DQ	FLAT:?RemotingClientReceivingReply@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z
	DQ	FLAT:?RemotingClientInvocationFinished@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?RemotingServerReceivingMessage@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z
	DQ	FLAT:?RemotingServerInvocationStarted@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?RemotingServerInvocationReturned@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?RemotingServerSendingReply@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z
	DQ	FLAT:?UnmanagedToManagedTransition@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z
	DQ	FLAT:?ManagedToUnmanagedTransition@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z
	DQ	FLAT:?RuntimeSuspendStarted@CCorProfilerCallbackImpl@@UEAAJW4__MIDL___MIDL_itf_corprof_0000_0006@@@Z
	DQ	FLAT:?RuntimeSuspendFinished@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?RuntimeSuspendAborted@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?RuntimeResumeStarted@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?RuntimeResumeFinished@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?RuntimeThreadSuspended@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?RuntimeThreadResumed@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?MovedReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_K0QEAK@Z
	DQ	FLAT:?ObjectAllocated@CCorProfilerCallbackImpl@@UEAAJ_K0@Z
	DQ	FLAT:?ObjectsAllocatedByClass@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAK@Z
	DQ	FLAT:?ObjectReferences@CCorProfilerCallbackImpl@@UEAAJ_K0KQEA_K@Z
	DQ	FLAT:?RootReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_K@Z
	DQ	FLAT:?ExceptionThrown@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ExceptionSearchFunctionEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ExceptionSearchFunctionLeave@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?ExceptionSearchFilterEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ExceptionSearchFilterLeave@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?ExceptionSearchCatcherFound@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ExceptionOSHandlerEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ExceptionOSHandlerLeave@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ExceptionUnwindFunctionEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ExceptionUnwindFunctionLeave@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?ExceptionUnwindFinallyEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z
	DQ	FLAT:?ExceptionUnwindFinallyLeave@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?ExceptionCatcherEnter@CCorProfilerCallbackImpl@@UEAAJ_K0@Z
	DQ	FLAT:?ExceptionCatcherLeave@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?COMClassicVTableCreated@CCorProfilerCallbackImpl@@UEAAJ_KAEBU_GUID@@PEAXK@Z
	DQ	FLAT:?COMClassicVTableDestroyed@CCorProfilerCallbackImpl@@UEAAJ_KAEBU_GUID@@PEAX@Z
	DQ	FLAT:?ExceptionCLRCatcherFound@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?ExceptionCLRCatcherExecute@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?ThreadNameChanged@CCorProfilerCallbackImpl@@UEAAJ_KKQEA_W@Z
	DQ	FLAT:?GarbageCollectionStarted@CCorProfilerCallbackImpl@@UEAAJHQEAHW4__MIDL___MIDL_itf_corprof_0011_0006@@@Z
	DQ	FLAT:?SurvivingReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAK@Z
	DQ	FLAT:?GarbageCollectionFinished@CCorProfilerCallbackImpl@@UEAAJXZ
	DQ	FLAT:?FinalizeableObjectQueued@CCorProfilerCallbackImpl@@UEAAJK_K@Z
	DQ	FLAT:?RootReferences2@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAW4__MIDL___MIDL_itf_corprof_0011_0001@@QEAW4__MIDL___MIDL_itf_corprof_0011_0002@@0@Z
	DQ	FLAT:?HandleCreated@CCorProfilerCallbackImpl@@UEAAJ_K0@Z
	DQ	FLAT:?HandleDestroyed@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_bad_alloc_Message DQ FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\corprofilercallbackimpl.cpp
;	COMDAT ?HandleDestroyed@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
handleID$ = 16
?HandleDestroyed@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::HandleDestroyed, COMDAT

; 408  :     return S_OK;

	xor	eax, eax

; 409  : }

	ret	0
?HandleDestroyed@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::HandleDestroyed
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?HandleCreated@CCorProfilerCallbackImpl@@UEAAJ_K0@Z
_TEXT	SEGMENT
this$ = 8
handleID$ = 16
initialObjectID$ = 24
?HandleCreated@CCorProfilerCallbackImpl@@UEAAJ_K0@Z PROC ; CCorProfilerCallbackImpl::HandleCreated, COMDAT

; 403  :     return S_OK;

	xor	eax, eax

; 404  : }

	ret	0
?HandleCreated@CCorProfilerCallbackImpl@@UEAAJ_K0@Z ENDP ; CCorProfilerCallbackImpl::HandleCreated
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RootReferences2@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAW4__MIDL___MIDL_itf_corprof_0011_0001@@QEAW4__MIDL___MIDL_itf_corprof_0011_0002@@0@Z
_TEXT	SEGMENT
this$ = 8
cRootRefs$ = 16
rootRefIDs$ = 24
rootKinds$ = 32
rootFlags$ = 40
rootIDs$ = 48
?RootReferences2@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAW4__MIDL___MIDL_itf_corprof_0011_0001@@QEAW4__MIDL___MIDL_itf_corprof_0011_0002@@0@Z PROC ; CCorProfilerCallbackImpl::RootReferences2, COMDAT

; 398  :     return S_OK;

	xor	eax, eax

; 399  : }

	ret	0
?RootReferences2@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAW4__MIDL___MIDL_itf_corprof_0011_0001@@QEAW4__MIDL___MIDL_itf_corprof_0011_0002@@0@Z ENDP ; CCorProfilerCallbackImpl::RootReferences2
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?FinalizeableObjectQueued@CCorProfilerCallbackImpl@@UEAAJK_K@Z
_TEXT	SEGMENT
this$ = 8
finalizerFlags$ = 16
objectID$ = 24
?FinalizeableObjectQueued@CCorProfilerCallbackImpl@@UEAAJK_K@Z PROC ; CCorProfilerCallbackImpl::FinalizeableObjectQueued, COMDAT

; 393  :     return S_OK;

	xor	eax, eax

; 394  : }

	ret	0
?FinalizeableObjectQueued@CCorProfilerCallbackImpl@@UEAAJK_K@Z ENDP ; CCorProfilerCallbackImpl::FinalizeableObjectQueued
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GarbageCollectionFinished@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?GarbageCollectionFinished@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::GarbageCollectionFinished, COMDAT

; 388  :     return S_OK;

	xor	eax, eax

; 389  : }

	ret	0
?GarbageCollectionFinished@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::GarbageCollectionFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?SurvivingReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAK@Z
_TEXT	SEGMENT
this$ = 8
cSurvivingObjectIDRanges$ = 16
objectIDRangeStart$ = 24
cObjectIDRangeLength$ = 32
?SurvivingReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAK@Z PROC ; CCorProfilerCallbackImpl::SurvivingReferences, COMDAT

; 383  :     return S_OK;

	xor	eax, eax

; 384  : }

	ret	0
?SurvivingReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAK@Z ENDP ; CCorProfilerCallbackImpl::SurvivingReferences
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GarbageCollectionStarted@CCorProfilerCallbackImpl@@UEAAJHQEAHW4__MIDL___MIDL_itf_corprof_0011_0006@@@Z
_TEXT	SEGMENT
this$ = 8
cGenerations$ = 16
generationCollected$ = 24
reason$ = 32
?GarbageCollectionStarted@CCorProfilerCallbackImpl@@UEAAJHQEAHW4__MIDL___MIDL_itf_corprof_0011_0006@@@Z PROC ; CCorProfilerCallbackImpl::GarbageCollectionStarted, COMDAT

; 378  : 	return S_OK;

	xor	eax, eax

; 379  : }

	ret	0
?GarbageCollectionStarted@CCorProfilerCallbackImpl@@UEAAJHQEAHW4__MIDL___MIDL_itf_corprof_0011_0006@@@Z ENDP ; CCorProfilerCallbackImpl::GarbageCollectionStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ThreadNameChanged@CCorProfilerCallbackImpl@@UEAAJ_KKQEA_W@Z
_TEXT	SEGMENT
this$ = 8
threadID$ = 16
cchName$ = 24
name$ = 32
?ThreadNameChanged@CCorProfilerCallbackImpl@@UEAAJ_KKQEA_W@Z PROC ; CCorProfilerCallbackImpl::ThreadNameChanged, COMDAT

; 373  : 	return S_OK;

	xor	eax, eax

; 374  : }

	ret	0
?ThreadNameChanged@CCorProfilerCallbackImpl@@UEAAJ_KKQEA_W@Z ENDP ; CCorProfilerCallbackImpl::ThreadNameChanged
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?COMClassicVTableDestroyed@CCorProfilerCallbackImpl@@UEAAJ_KAEBU_GUID@@PEAX@Z
_TEXT	SEGMENT
this$ = 8
wrappedClassID$ = 16
implementedIID$ = 24
pVTable$ = 32
?COMClassicVTableDestroyed@CCorProfilerCallbackImpl@@UEAAJ_KAEBU_GUID@@PEAX@Z PROC ; CCorProfilerCallbackImpl::COMClassicVTableDestroyed, COMDAT

; 368  :     return S_OK;

	xor	eax, eax

; 369  : }

	ret	0
?COMClassicVTableDestroyed@CCorProfilerCallbackImpl@@UEAAJ_KAEBU_GUID@@PEAX@Z ENDP ; CCorProfilerCallbackImpl::COMClassicVTableDestroyed
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?COMClassicVTableCreated@CCorProfilerCallbackImpl@@UEAAJ_KAEBU_GUID@@PEAXK@Z
_TEXT	SEGMENT
this$ = 8
wrappedClassID$ = 16
implementedIID$ = 24
pVTable$ = 32
cSlots$ = 40
?COMClassicVTableCreated@CCorProfilerCallbackImpl@@UEAAJ_KAEBU_GUID@@PEAXK@Z PROC ; CCorProfilerCallbackImpl::COMClassicVTableCreated, COMDAT

; 363  :     return S_OK;

	xor	eax, eax

; 364  : }

	ret	0
?COMClassicVTableCreated@CCorProfilerCallbackImpl@@UEAAJ_KAEBU_GUID@@PEAXK@Z ENDP ; CCorProfilerCallbackImpl::COMClassicVTableCreated
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionCatcherLeave@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?ExceptionCatcherLeave@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::ExceptionCatcherLeave, COMDAT

; 358  :     return S_OK;

	xor	eax, eax

; 359  : }

	ret	0
?ExceptionCatcherLeave@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionCatcherLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionCatcherEnter@CCorProfilerCallbackImpl@@UEAAJ_K0@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
objectID$ = 24
?ExceptionCatcherEnter@CCorProfilerCallbackImpl@@UEAAJ_K0@Z PROC ; CCorProfilerCallbackImpl::ExceptionCatcherEnter, COMDAT

; 353  :     return S_OK;

	xor	eax, eax

; 354  : }

	ret	0
?ExceptionCatcherEnter@CCorProfilerCallbackImpl@@UEAAJ_K0@Z ENDP ; CCorProfilerCallbackImpl::ExceptionCatcherEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionUnwindFinallyLeave@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?ExceptionUnwindFinallyLeave@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyLeave, COMDAT

; 347  :     return S_OK;

	xor	eax, eax

; 348  : }

	ret	0
?ExceptionUnwindFinallyLeave@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionUnwindFinallyEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
?ExceptionUnwindFinallyEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyEnter, COMDAT

; 342  :     return S_OK;

	xor	eax, eax

; 343  : }

	ret	0
?ExceptionUnwindFinallyEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionOSHandlerLeave@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
?ExceptionOSHandlerLeave@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ExceptionOSHandlerLeave, COMDAT

; 337  :     return S_OK;

	xor	eax, eax

; 338  : }

	ret	0
?ExceptionOSHandlerLeave@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ExceptionOSHandlerLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionOSHandlerEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
?ExceptionOSHandlerEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ExceptionOSHandlerEnter, COMDAT

; 332  :     return S_OK;

	xor	eax, eax

; 333  : }

	ret	0
?ExceptionOSHandlerEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ExceptionOSHandlerEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionCLRCatcherExecute@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?ExceptionCLRCatcherExecute@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::ExceptionCLRCatcherExecute, COMDAT

; 327  :     return S_OK;

	xor	eax, eax

; 328  : }

	ret	0
?ExceptionCLRCatcherExecute@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionCLRCatcherExecute
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionCLRCatcherFound@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?ExceptionCLRCatcherFound@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::ExceptionCLRCatcherFound, COMDAT

; 322  :     return S_OK;

	xor	eax, eax

; 323  : }

	ret	0
?ExceptionCLRCatcherFound@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionCLRCatcherFound
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionSearchCatcherFound@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
?ExceptionSearchCatcherFound@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ExceptionSearchCatcherFound, COMDAT

; 317  :     return S_OK;

	xor	eax, eax

; 318  : }

	ret	0
?ExceptionSearchCatcherFound@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ExceptionSearchCatcherFound
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionSearchFilterLeave@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?ExceptionSearchFilterLeave@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::ExceptionSearchFilterLeave, COMDAT

; 312  :     return S_OK;

	xor	eax, eax

; 313  : }

	ret	0
?ExceptionSearchFilterLeave@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionSearchFilterLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionSearchFilterEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
?ExceptionSearchFilterEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ExceptionSearchFilterEnter, COMDAT

; 307  :     return S_OK;

	xor	eax, eax

; 308  : }

	ret	0
?ExceptionSearchFilterEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ExceptionSearchFilterEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionSearchFunctionLeave@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?ExceptionSearchFunctionLeave@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::ExceptionSearchFunctionLeave, COMDAT

; 302  :     return S_OK;

	xor	eax, eax

; 303  : }

	ret	0
?ExceptionSearchFunctionLeave@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionSearchFunctionLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionSearchFunctionEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
?ExceptionSearchFunctionEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ExceptionSearchFunctionEnter, COMDAT

; 297  :     return S_OK;

	xor	eax, eax

; 298  : }

	ret	0
?ExceptionSearchFunctionEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ExceptionSearchFunctionEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionUnwindFunctionLeave@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?ExceptionUnwindFunctionLeave@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionLeave, COMDAT

; 292  :     return S_OK;

	xor	eax, eax

; 293  : }

	ret	0
?ExceptionUnwindFunctionLeave@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionUnwindFunctionEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
?ExceptionUnwindFunctionEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionEnter, COMDAT

; 287  :     return S_OK;

	xor	eax, eax

; 288  : }

	ret	0
?ExceptionUnwindFunctionEnter@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionThrown@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
thrownObjectID$ = 16
?ExceptionThrown@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ExceptionThrown, COMDAT

; 282  :     return S_OK;

	xor	eax, eax

; 283  : }

	ret	0
?ExceptionThrown@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ExceptionThrown
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RootReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_K@Z
_TEXT	SEGMENT
this$ = 8
rootRefs$ = 16
rootRefIDs$ = 24
?RootReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_K@Z PROC ; CCorProfilerCallbackImpl::RootReferences, COMDAT

; 277  :     return S_OK;

	xor	eax, eax

; 278  : }

	ret	0
?RootReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_K@Z ENDP ; CCorProfilerCallbackImpl::RootReferences
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ObjectReferences@CCorProfilerCallbackImpl@@UEAAJ_K0KQEA_K@Z
_TEXT	SEGMENT
this$ = 8
objectID$ = 16
classID$ = 24
objectRefs$ = 32
objectRefIDs$ = 40
?ObjectReferences@CCorProfilerCallbackImpl@@UEAAJ_K0KQEA_K@Z PROC ; CCorProfilerCallbackImpl::ObjectReferences, COMDAT

; 272  :     return S_OK;

	xor	eax, eax

; 273  : }

	ret	0
?ObjectReferences@CCorProfilerCallbackImpl@@UEAAJ_K0KQEA_K@Z ENDP ; CCorProfilerCallbackImpl::ObjectReferences
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ObjectsAllocatedByClass@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAK@Z
_TEXT	SEGMENT
this$ = 8
classCount$ = 16
classIDs$ = 24
objects$ = 32
?ObjectsAllocatedByClass@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAK@Z PROC ; CCorProfilerCallbackImpl::ObjectsAllocatedByClass, COMDAT

; 267  :     return S_OK;

	xor	eax, eax

; 268  : }

	ret	0
?ObjectsAllocatedByClass@CCorProfilerCallbackImpl@@UEAAJKQEA_KQEAK@Z ENDP ; CCorProfilerCallbackImpl::ObjectsAllocatedByClass
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ObjectAllocated@CCorProfilerCallbackImpl@@UEAAJ_K0@Z
_TEXT	SEGMENT
this$ = 8
objectID$ = 16
classID$ = 24
?ObjectAllocated@CCorProfilerCallbackImpl@@UEAAJ_K0@Z PROC ; CCorProfilerCallbackImpl::ObjectAllocated, COMDAT

; 262  :     return S_OK;

	xor	eax, eax

; 263  : }

	ret	0
?ObjectAllocated@CCorProfilerCallbackImpl@@UEAAJ_K0@Z ENDP ; CCorProfilerCallbackImpl::ObjectAllocated
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?MovedReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_K0QEAK@Z
_TEXT	SEGMENT
this$ = 8
cmovedObjectIDRanges$ = 16
oldObjectIDRangeStart$ = 24
newObjectIDRangeStart$ = 32
cObjectIDRangeLength$ = 40
?MovedReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_K0QEAK@Z PROC ; CCorProfilerCallbackImpl::MovedReferences, COMDAT

; 257  :     return S_OK;

	xor	eax, eax

; 258  : }

	ret	0
?MovedReferences@CCorProfilerCallbackImpl@@UEAAJKQEA_K0QEAK@Z ENDP ; CCorProfilerCallbackImpl::MovedReferences
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeThreadResumed@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
threadID$ = 16
?RuntimeThreadResumed@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::RuntimeThreadResumed, COMDAT

; 252  :     return S_OK;

	xor	eax, eax

; 253  : }

	ret	0
?RuntimeThreadResumed@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::RuntimeThreadResumed
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeThreadSuspended@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
threadID$ = 16
?RuntimeThreadSuspended@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::RuntimeThreadSuspended, COMDAT

; 247  :     return S_OK;

	xor	eax, eax

; 248  : }

	ret	0
?RuntimeThreadSuspended@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::RuntimeThreadSuspended
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeResumeFinished@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?RuntimeResumeFinished@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::RuntimeResumeFinished, COMDAT

; 242  :     return S_OK;

	xor	eax, eax

; 243  : }

	ret	0
?RuntimeResumeFinished@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::RuntimeResumeFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeResumeStarted@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?RuntimeResumeStarted@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::RuntimeResumeStarted, COMDAT

; 237  :     return S_OK;

	xor	eax, eax

; 238  : }

	ret	0
?RuntimeResumeStarted@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::RuntimeResumeStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeSuspendAborted@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?RuntimeSuspendAborted@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::RuntimeSuspendAborted, COMDAT

; 232  :     return S_OK;

	xor	eax, eax

; 233  : }

	ret	0
?RuntimeSuspendAborted@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::RuntimeSuspendAborted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeSuspendFinished@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?RuntimeSuspendFinished@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::RuntimeSuspendFinished, COMDAT

; 227  :     return S_OK;

	xor	eax, eax

; 228  : }

	ret	0
?RuntimeSuspendFinished@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::RuntimeSuspendFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeSuspendStarted@CCorProfilerCallbackImpl@@UEAAJW4__MIDL___MIDL_itf_corprof_0000_0006@@@Z
_TEXT	SEGMENT
this$ = 8
suspendReason$ = 16
?RuntimeSuspendStarted@CCorProfilerCallbackImpl@@UEAAJW4__MIDL___MIDL_itf_corprof_0000_0006@@@Z PROC ; CCorProfilerCallbackImpl::RuntimeSuspendStarted, COMDAT

; 222  :     return S_OK;

	xor	eax, eax

; 223  : }

	ret	0
?RuntimeSuspendStarted@CCorProfilerCallbackImpl@@UEAAJW4__MIDL___MIDL_itf_corprof_0000_0006@@@Z ENDP ; CCorProfilerCallbackImpl::RuntimeSuspendStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingServerSendingReply@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z
_TEXT	SEGMENT
this$ = 8
pCookie$ = 16
fIsAsync$ = 24
?RemotingServerSendingReply@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z PROC ; CCorProfilerCallbackImpl::RemotingServerSendingReply, COMDAT

; 217  :     return S_OK;

	xor	eax, eax

; 218  : }

	ret	0
?RemotingServerSendingReply@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z ENDP ; CCorProfilerCallbackImpl::RemotingServerSendingReply
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingServerInvocationReturned@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?RemotingServerInvocationReturned@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::RemotingServerInvocationReturned, COMDAT

; 212  :     return S_OK;

	xor	eax, eax

; 213  : }

	ret	0
?RemotingServerInvocationReturned@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::RemotingServerInvocationReturned
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingServerInvocationStarted@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?RemotingServerInvocationStarted@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::RemotingServerInvocationStarted, COMDAT

; 207  :     return S_OK;

	xor	eax, eax

; 208  : }

	ret	0
?RemotingServerInvocationStarted@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::RemotingServerInvocationStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingServerReceivingMessage@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z
_TEXT	SEGMENT
this$ = 8
pCookie$ = 16
fIsAsync$ = 24
?RemotingServerReceivingMessage@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z PROC ; CCorProfilerCallbackImpl::RemotingServerReceivingMessage, COMDAT

; 202  :     return S_OK;

	xor	eax, eax

; 203  : }

	ret	0
?RemotingServerReceivingMessage@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z ENDP ; CCorProfilerCallbackImpl::RemotingServerReceivingMessage
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingClientInvocationFinished@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?RemotingClientInvocationFinished@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::RemotingClientInvocationFinished, COMDAT

; 197  : 	return S_OK;

	xor	eax, eax

; 198  : }

	ret	0
?RemotingClientInvocationFinished@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::RemotingClientInvocationFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingClientReceivingReply@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z
_TEXT	SEGMENT
this$ = 8
pCookie$ = 16
fIsAsync$ = 24
?RemotingClientReceivingReply@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z PROC ; CCorProfilerCallbackImpl::RemotingClientReceivingReply, COMDAT

; 192  :     return S_OK;

	xor	eax, eax

; 193  : }

	ret	0
?RemotingClientReceivingReply@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z ENDP ; CCorProfilerCallbackImpl::RemotingClientReceivingReply
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingClientSendingMessage@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z
_TEXT	SEGMENT
this$ = 8
pCookie$ = 16
fIsAsync$ = 24
?RemotingClientSendingMessage@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z PROC ; CCorProfilerCallbackImpl::RemotingClientSendingMessage, COMDAT

; 187  :     return S_OK;

	xor	eax, eax

; 188  : }

	ret	0
?RemotingClientSendingMessage@CCorProfilerCallbackImpl@@UEAAJPEAU_GUID@@H@Z ENDP ; CCorProfilerCallbackImpl::RemotingClientSendingMessage
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingClientInvocationStarted@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?RemotingClientInvocationStarted@CCorProfilerCallbackImpl@@UEAAJXZ PROC ; CCorProfilerCallbackImpl::RemotingClientInvocationStarted, COMDAT

; 182  :     return S_OK;

	xor	eax, eax

; 183  : }

	ret	0
?RemotingClientInvocationStarted@CCorProfilerCallbackImpl@@UEAAJXZ ENDP ; CCorProfilerCallbackImpl::RemotingClientInvocationStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ThreadAssignedToOSThread@CCorProfilerCallbackImpl@@UEAAJ_KK@Z
_TEXT	SEGMENT
this$ = 8
managedThreadID$ = 16
osThreadID$ = 24
?ThreadAssignedToOSThread@CCorProfilerCallbackImpl@@UEAAJ_KK@Z PROC ; CCorProfilerCallbackImpl::ThreadAssignedToOSThread, COMDAT

; 177  :     return S_OK;

	xor	eax, eax

; 178  : }

	ret	0
?ThreadAssignedToOSThread@CCorProfilerCallbackImpl@@UEAAJ_KK@Z ENDP ; CCorProfilerCallbackImpl::ThreadAssignedToOSThread
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ThreadDestroyed@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
threadID$ = 16
?ThreadDestroyed@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ThreadDestroyed, COMDAT

; 172  :     return S_OK;

	xor	eax, eax

; 173  : }

	ret	0
?ThreadDestroyed@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ThreadDestroyed
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ThreadCreated@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
threadID$ = 16
?ThreadCreated@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC	; CCorProfilerCallbackImpl::ThreadCreated, COMDAT

; 167  :     return S_OK;

	xor	eax, eax

; 168  : }

	ret	0
?ThreadCreated@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP	; CCorProfilerCallbackImpl::ThreadCreated
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ManagedToUnmanagedTransition@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
reason$ = 24
?ManagedToUnmanagedTransition@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z PROC ; CCorProfilerCallbackImpl::ManagedToUnmanagedTransition, COMDAT

; 162  :     return S_OK;

	xor	eax, eax

; 163  : }

	ret	0
?ManagedToUnmanagedTransition@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z ENDP ; CCorProfilerCallbackImpl::ManagedToUnmanagedTransition
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?UnmanagedToManagedTransition@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
reason$ = 24
?UnmanagedToManagedTransition@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z PROC ; CCorProfilerCallbackImpl::UnmanagedToManagedTransition, COMDAT

; 157  :     return S_OK;

	xor	eax, eax

; 158  : }

	ret	0
?UnmanagedToManagedTransition@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z ENDP ; CCorProfilerCallbackImpl::UnmanagedToManagedTransition
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITInlining@CCorProfilerCallbackImpl@@UEAAJ_K0PEAH@Z
_TEXT	SEGMENT
this$ = 8
callerID$ = 16
calleeID$ = 24
pfShouldInline$ = 32
?JITInlining@CCorProfilerCallbackImpl@@UEAAJ_K0PEAH@Z PROC ; CCorProfilerCallbackImpl::JITInlining, COMDAT

; 152  :     return S_OK;

	xor	eax, eax

; 153  : }

	ret	0
?JITInlining@CCorProfilerCallbackImpl@@UEAAJ_K0PEAH@Z ENDP ; CCorProfilerCallbackImpl::JITInlining
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITFunctionPitched@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
?JITFunctionPitched@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::JITFunctionPitched, COMDAT

; 147  :     return S_OK;

	xor	eax, eax

; 148  : }

	ret	0
?JITFunctionPitched@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::JITFunctionPitched
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITCachedFunctionSearchFinished@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0004@@@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
result$ = 24
?JITCachedFunctionSearchFinished@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0004@@@Z PROC ; CCorProfilerCallbackImpl::JITCachedFunctionSearchFinished, COMDAT

; 142  :     return S_OK;

	xor	eax, eax

; 143  : }

	ret	0
?JITCachedFunctionSearchFinished@CCorProfilerCallbackImpl@@UEAAJ_KW4__MIDL___MIDL_itf_corprof_0000_0004@@@Z ENDP ; CCorProfilerCallbackImpl::JITCachedFunctionSearchFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITCachedFunctionSearchStarted@CCorProfilerCallbackImpl@@UEAAJ_KPEAH@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
pbUseCachedFunction$ = 24
?JITCachedFunctionSearchStarted@CCorProfilerCallbackImpl@@UEAAJ_KPEAH@Z PROC ; CCorProfilerCallbackImpl::JITCachedFunctionSearchStarted, COMDAT

; 137  :     return S_OK;

	xor	eax, eax

; 138  : }

	ret	0
?JITCachedFunctionSearchStarted@CCorProfilerCallbackImpl@@UEAAJ_KPEAH@Z ENDP ; CCorProfilerCallbackImpl::JITCachedFunctionSearchStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITCompilationFinished@CCorProfilerCallbackImpl@@UEAAJ_KJH@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
hrStatus$ = 24
fIsSafeToBlock$ = 32
?JITCompilationFinished@CCorProfilerCallbackImpl@@UEAAJ_KJH@Z PROC ; CCorProfilerCallbackImpl::JITCompilationFinished, COMDAT

; 132  :     return S_OK;

	xor	eax, eax

; 133  : }

	ret	0
?JITCompilationFinished@CCorProfilerCallbackImpl@@UEAAJ_KJH@Z ENDP ; CCorProfilerCallbackImpl::JITCompilationFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITCompilationStarted@CCorProfilerCallbackImpl@@UEAAJ_KH@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
fIsSafeToBlock$ = 24
?JITCompilationStarted@CCorProfilerCallbackImpl@@UEAAJ_KH@Z PROC ; CCorProfilerCallbackImpl::JITCompilationStarted, COMDAT

; 127  :     return S_OK;

	xor	eax, eax

; 128  : }

	ret	0
?JITCompilationStarted@CCorProfilerCallbackImpl@@UEAAJ_KH@Z ENDP ; CCorProfilerCallbackImpl::JITCompilationStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?FunctionUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
functionID$ = 16
?FunctionUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::FunctionUnloadStarted, COMDAT

; 122  :     return S_OK;

	xor	eax, eax

; 123  : }

	ret	0
?FunctionUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::FunctionUnloadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ClassUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
_TEXT	SEGMENT
this$ = 8
classID$ = 16
hrStatus$ = 24
?ClassUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z PROC ; CCorProfilerCallbackImpl::ClassUnloadFinished, COMDAT

; 117  :     return S_OK;

	xor	eax, eax

; 118  : }

	ret	0
?ClassUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ENDP ; CCorProfilerCallbackImpl::ClassUnloadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ClassUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
classID$ = 16
?ClassUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ClassUnloadStarted, COMDAT

; 112  :     return S_OK;

	xor	eax, eax

; 113  : }

	ret	0
?ClassUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ClassUnloadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ClassLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
_TEXT	SEGMENT
this$ = 8
classID$ = 16
hrStatus$ = 24
?ClassLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z PROC ; CCorProfilerCallbackImpl::ClassLoadFinished, COMDAT

; 107  :     return S_OK;

	xor	eax, eax

; 108  : }

	ret	0
?ClassLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ENDP ; CCorProfilerCallbackImpl::ClassLoadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ClassLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
classID$ = 16
?ClassLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ClassLoadStarted, COMDAT

; 102  :     return S_OK;

	xor	eax, eax

; 103  : }

	ret	0
?ClassLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ClassLoadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ModuleAttachedToAssembly@CCorProfilerCallbackImpl@@UEAAJ_K0@Z
_TEXT	SEGMENT
this$ = 8
moduleID$ = 16
assemblyID$ = 24
?ModuleAttachedToAssembly@CCorProfilerCallbackImpl@@UEAAJ_K0@Z PROC ; CCorProfilerCallbackImpl::ModuleAttachedToAssembly, COMDAT

; 97   :     return S_OK;

	xor	eax, eax

; 98   : }

	ret	0
?ModuleAttachedToAssembly@CCorProfilerCallbackImpl@@UEAAJ_K0@Z ENDP ; CCorProfilerCallbackImpl::ModuleAttachedToAssembly
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ModuleUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
_TEXT	SEGMENT
this$ = 8
moduleID$ = 16
hrStatus$ = 24
?ModuleUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z PROC ; CCorProfilerCallbackImpl::ModuleUnloadFinished, COMDAT

; 92   : 	return S_OK;

	xor	eax, eax

; 93   : }

	ret	0
?ModuleUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ENDP ; CCorProfilerCallbackImpl::ModuleUnloadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ModuleUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
moduleID$ = 16
?ModuleUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ModuleUnloadStarted, COMDAT

; 87   :     return S_OK;

	xor	eax, eax

; 88   : }

	ret	0
?ModuleUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ModuleUnloadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ModuleLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
_TEXT	SEGMENT
this$ = 8
moduleID$ = 16
hrStatus$ = 24
?ModuleLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z PROC ; CCorProfilerCallbackImpl::ModuleLoadFinished, COMDAT

; 82   :     return S_OK;

	xor	eax, eax

; 83   : }

	ret	0
?ModuleLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ENDP ; CCorProfilerCallbackImpl::ModuleLoadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ModuleLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
moduleID$ = 16
?ModuleLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::ModuleLoadStarted, COMDAT

; 77   :     return S_OK;

	xor	eax, eax

; 78   : }

	ret	0
?ModuleLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::ModuleLoadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AssemblyUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
_TEXT	SEGMENT
this$ = 8
assemblyID$ = 16
hrStatus$ = 24
?AssemblyUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z PROC ; CCorProfilerCallbackImpl::AssemblyUnloadFinished, COMDAT

; 72   :     return S_OK;

	xor	eax, eax

; 73   : }

	ret	0
?AssemblyUnloadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ENDP ; CCorProfilerCallbackImpl::AssemblyUnloadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AssemblyUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
assemblyID$ = 16
?AssemblyUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::AssemblyUnloadStarted, COMDAT

; 67   :     return S_OK;

	xor	eax, eax

; 68   : }

	ret	0
?AssemblyUnloadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::AssemblyUnloadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AssemblyLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
_TEXT	SEGMENT
this$ = 8
assemblyID$ = 16
hrStatus$ = 24
?AssemblyLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z PROC ; CCorProfilerCallbackImpl::AssemblyLoadFinished, COMDAT

; 62   :     return S_OK;

	xor	eax, eax

; 63   : }

	ret	0
?AssemblyLoadFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ENDP ; CCorProfilerCallbackImpl::AssemblyLoadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AssemblyLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
assemblyID$ = 16
?AssemblyLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::AssemblyLoadStarted, COMDAT

; 57   :     return S_OK;

	xor	eax, eax

; 58   : }

	ret	0
?AssemblyLoadStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::AssemblyLoadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AppDomainShutdownFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
_TEXT	SEGMENT
this$ = 8
appDomainID$ = 16
hrStatus$ = 24
?AppDomainShutdownFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z PROC ; CCorProfilerCallbackImpl::AppDomainShutdownFinished, COMDAT

; 52   :     return S_OK;

	xor	eax, eax

; 53   : }

	ret	0
?AppDomainShutdownFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ENDP ; CCorProfilerCallbackImpl::AppDomainShutdownFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AppDomainShutdownStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
appDomainID$ = 16
?AppDomainShutdownStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::AppDomainShutdownStarted, COMDAT

; 47   :     return S_OK;

	xor	eax, eax

; 48   : }

	ret	0
?AppDomainShutdownStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::AppDomainShutdownStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AppDomainCreationFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z
_TEXT	SEGMENT
this$ = 8
appDomainID$ = 16
hrStatus$ = 24
?AppDomainCreationFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z PROC ; CCorProfilerCallbackImpl::AppDomainCreationFinished, COMDAT

; 42   :     return S_OK;

	xor	eax, eax

; 43   : }

	ret	0
?AppDomainCreationFinished@CCorProfilerCallbackImpl@@UEAAJ_KJ@Z ENDP ; CCorProfilerCallbackImpl::AppDomainCreationFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AppDomainCreationStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z
_TEXT	SEGMENT
this$ = 8
appDomainID$ = 16
?AppDomainCreationStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z PROC ; CCorProfilerCallbackImpl::AppDomainCreationStarted, COMDAT

; 37   :     return S_OK;

	xor	eax, eax

; 38   : }

	ret	0
?AppDomainCreationStarted@CCorProfilerCallbackImpl@@UEAAJ_K@Z ENDP ; CCorProfilerCallbackImpl::AppDomainCreationStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?Shutdown@CCorProfilerCallbackImpl@@UEAAJXZ
_TEXT	SEGMENT
this$ = 8
?Shutdown@CCorProfilerCallbackImpl@@UEAAJXZ PROC	; CCorProfilerCallbackImpl::Shutdown, COMDAT

; 32   :     return S_OK;

	xor	eax, eax

; 33   : }

	ret	0
?Shutdown@CCorProfilerCallbackImpl@@UEAAJXZ ENDP	; CCorProfilerCallbackImpl::Shutdown
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?Initialize@CCorProfilerCallbackImpl@@UEAAJPEAUIUnknown@@@Z
_TEXT	SEGMENT
this$ = 8
pICorProfilerInfoUnk$ = 16
?Initialize@CCorProfilerCallbackImpl@@UEAAJPEAUIUnknown@@@Z PROC ; CCorProfilerCallbackImpl::Initialize, COMDAT

; 27   :     return S_OK;

	xor	eax, eax

; 28   : }

	ret	0
?Initialize@CCorProfilerCallbackImpl@@UEAAJPEAUIUnknown@@@Z ENDP ; CCorProfilerCallbackImpl::Initialize
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ??0IUnknown@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0IUnknown@@QEAA@XZ PROC				; IUnknown::IUnknown, COMDAT
	mov	rax, rcx
	ret	0
??0IUnknown@@QEAA@XZ ENDP				; IUnknown::IUnknown
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ??0ICorProfilerCallback@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0ICorProfilerCallback@@QEAA@XZ PROC			; ICorProfilerCallback::ICorProfilerCallback, COMDAT
	lea	rax, OFFSET FLAT:?profiler@@3VCProfiler@@A ; profiler
	ret	0
??0ICorProfilerCallback@@QEAA@XZ ENDP			; ICorProfilerCallback::ICorProfilerCallback
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ??0ICorProfilerCallback2@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0ICorProfilerCallback2@@QEAA@XZ PROC			; ICorProfilerCallback2::ICorProfilerCallback2, COMDAT
	lea	rax, OFFSET FLAT:?profiler@@3VCProfiler@@A ; profiler
	ret	0
??0ICorProfilerCallback2@@QEAA@XZ ENDP			; ICorProfilerCallback2::ICorProfilerCallback2
_TEXT	ENDS
PUBLIC	??0CCorProfilerCallbackImpl@@QEAA@XZ		; CCorProfilerCallbackImpl::CCorProfilerCallbackImpl
; Function compile flags: /Ogtpy
;	COMDAT ??0CCorProfilerCallbackImpl@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0CCorProfilerCallbackImpl@@QEAA@XZ PROC		; CCorProfilerCallbackImpl::CCorProfilerCallbackImpl, COMDAT

; 23   : CCorProfilerCallbackImpl::CCorProfilerCallbackImpl() {}

	lea	rax, OFFSET FLAT:??_7CCorProfilerCallbackImpl@@6B@
	mov	QWORD PTR ?profiler@@3VCProfiler@@A, rax
	lea	rax, OFFSET FLAT:?profiler@@3VCProfiler@@A ; profiler
	ret	0
??0CCorProfilerCallbackImpl@@QEAA@XZ ENDP		; CCorProfilerCallbackImpl::CCorProfilerCallbackImpl
END
