; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BI@BBOPOAJD@Local?2Profiler?4Event?4?$CFd?$AA@ ; `string'
EXTRN	__imp_OpenEventA:PROC
EXTRN	__imp_SetEvent:PROC
EXTRN	__imp_ResetEvent:PROC
EXTRN	__imp_WaitForSingleObject:PROC
EXTRN	??2@YAPEAX_K@Z:PROC				; operator new
EXTRN	??3@YAXPEAX@Z:PROC				; operator delete
EXTRN	__imp_sprintf_s:PROC
EXTRN	??_U@YAPEAX_K@Z:PROC				; operator new[]
;	COMDAT ??_C@_0BI@BBOPOAJD@Local?2Profiler?4Event?4?$CFd?$AA@
CONST	SEGMENT
??_C@_0BI@BBOPOAJD@Local?2Profiler?4Event?4?$CFd?$AA@ DB 'Local\Profiler.'
	DB	'Event.%d', 00H				; `string'
_bad_alloc_Message DQ FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
PUBLIC	?GetEventName@@YAPEADH@Z			; GetEventName
;	COMDAT pdata
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\eventwaithandle.cpp
pdata	SEGMENT
$pdata$?GetEventName@@YAPEADH@Z DD imagerel $LN3
	DD	imagerel $LN3+63
	DD	imagerel $unwind$?GetEventName@@YAPEADH@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?GetEventName@@YAPEADH@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
; Function compile flags: /Ogtpy
xdata	ENDS
;	COMDAT ?GetEventName@@YAPEADH@Z
_TEXT	SEGMENT
eventName$ = 48
?GetEventName@@YAPEADH@Z PROC				; GetEventName, COMDAT

; 65   : {

$LN3:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	ebx, ecx

; 66   : 	char *evName = new char[128];

	mov	ecx, 128				; 00000080H
	call	??_U@YAPEAX_K@Z				; operator new[]

; 67   : 	sprintf_s(evName, 128, "Local\\Profiler.Event.%d", eventName);

	lea	r8, OFFSET FLAT:??_C@_0BI@BBOPOAJD@Local?2Profiler?4Event?4?$CFd?$AA@
	mov	r9d, ebx
	mov	rcx, rax
	mov	edx, 128				; 00000080H
	mov	rdi, rax
	call	QWORD PTR __imp_sprintf_s

; 68   : 	
; 69   : 	return evName;
; 70   : }

	mov	rbx, QWORD PTR [rsp+48]
	mov	rax, rdi
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
?GetEventName@@YAPEADH@Z ENDP				; GetEventName
_TEXT	ENDS
PUBLIC	?GetEventHandle@CEventWaitHandle@@QEAAPEAXXZ	; CEventWaitHandle::GetEventHandle
; Function compile flags: /Ogtpy
;	COMDAT ?GetEventHandle@CEventWaitHandle@@QEAAPEAXXZ
_TEXT	SEGMENT
this$ = 8
?GetEventHandle@CEventWaitHandle@@QEAAPEAXXZ PROC	; CEventWaitHandle::GetEventHandle, COMDAT

; 47   : 	return this->eventHandle;

	mov	rax, QWORD PTR [rcx+8]

; 48   : }

	ret	0
?GetEventHandle@CEventWaitHandle@@QEAAPEAXXZ ENDP	; CEventWaitHandle::GetEventHandle
_TEXT	ENDS
PUBLIC	?Wait@CEventWaitHandle@@QEAAKH@Z		; CEventWaitHandle::Wait
; Function compile flags: /Ogtpy
;	COMDAT ?Wait@CEventWaitHandle@@QEAAKH@Z
_TEXT	SEGMENT
this$ = 8
milliseconds$ = 16
?Wait@CEventWaitHandle@@QEAAKH@Z PROC			; CEventWaitHandle::Wait, COMDAT

; 36   : 	return WaitForSingleObject(this->eventHandle, milliseconds);

	mov	rcx, QWORD PTR [rcx+8]
	or	edx, -1					; ffffffffH

; 37   : }

	rex_jmp	QWORD PTR __imp_WaitForSingleObject
?Wait@CEventWaitHandle@@QEAAKH@Z ENDP			; CEventWaitHandle::Wait
_TEXT	ENDS
PUBLIC	?Set@CEventWaitHandle@@QEAA_NXZ			; CEventWaitHandle::Set
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Set@CEventWaitHandle@@QEAA_NXZ DD imagerel $LN3
	DD	imagerel $LN3+24
	DD	imagerel $unwind$?Set@CEventWaitHandle@@QEAA_NXZ
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Set@CEventWaitHandle@@QEAA_NXZ DD 010401H
	DD	04204H
; Function compile flags: /Ogtpy
xdata	ENDS
;	COMDAT ?Set@CEventWaitHandle@@QEAA_NXZ
_TEXT	SEGMENT
this$ = 48
?Set@CEventWaitHandle@@QEAA_NXZ PROC			; CEventWaitHandle::Set, COMDAT

; 23   : {

$LN3:
	sub	rsp, 40					; 00000028H

; 24   : 	return SetEvent(this->eventHandle) != 0;

	mov	rcx, QWORD PTR [rcx+8]
	call	QWORD PTR __imp_SetEvent
	test	eax, eax
	setne	al

; 25   : }

	add	rsp, 40					; 00000028H
	ret	0
?Set@CEventWaitHandle@@QEAA_NXZ ENDP			; CEventWaitHandle::Set
_TEXT	ENDS
PUBLIC	??0CEventWaitHandle@@QEAA@PEAD@Z		; CEventWaitHandle::CEventWaitHandle
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0CEventWaitHandle@@QEAA@PEAD@Z DD imagerel $LN3
	DD	imagerel $LN3+41
	DD	imagerel $unwind$??0CEventWaitHandle@@QEAA@PEAD@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0CEventWaitHandle@@QEAA@PEAD@Z DD 020601H
	DD	030023206H
; Function compile flags: /Ogtpy
xdata	ENDS
;	COMDAT ??0CEventWaitHandle@@QEAA@PEAD@Z
_TEXT	SEGMENT
this$ = 48
name$ = 56
??0CEventWaitHandle@@QEAA@PEAD@Z PROC			; CEventWaitHandle::CEventWaitHandle, COMDAT

; 16   : {

$LN3:
	push	rbx
	sub	rsp, 32					; 00000020H

; 17   : 	this->name = name;

	mov	QWORD PTR [rcx], rdx
	mov	rbx, rcx

; 18   : 	this->eventHandle = OpenEventA(EVENT_MODIFY_STATE | SYNCHRONIZE, false, TEXT(this->name));

	mov	r8, rdx
	xor	edx, edx
	mov	ecx, 1048578				; 00100002H
	call	QWORD PTR __imp_OpenEventA
	mov	QWORD PTR [rbx+8], rax

; 19   : }

	mov	rax, rbx
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??0CEventWaitHandle@@QEAA@PEAD@Z ENDP			; CEventWaitHandle::CEventWaitHandle
PUBLIC	?OpenEventWaitHandle@@YAPEAVCEventWaitHandle@@PEAD@Z ; OpenEventWaitHandle
;	COMDAT pdata
pdata	SEGMENT
$pdata$?OpenEventWaitHandle@@YAPEAVCEventWaitHandle@@PEAD@Z DD imagerel $LN11
	DD	imagerel $LN11+100
	DD	imagerel $unwind$?OpenEventWaitHandle@@YAPEAVCEventWaitHandle@@PEAD@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?OpenEventWaitHandle@@YAPEAVCEventWaitHandle@@PEAD@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
; Function compile flags: /Ogtpy
xdata	ENDS
;	COMDAT ?OpenEventWaitHandle@@YAPEAVCEventWaitHandle@@PEAD@Z
_TEXT	SEGMENT
name$ = 48
?OpenEventWaitHandle@@YAPEAVCEventWaitHandle@@PEAD@Z PROC ; OpenEventWaitHandle, COMDAT

; 52   : {

$LN11:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rdi, rcx

; 53   : 	CEventWaitHandle *handle = new CEventWaitHandle(name);

	mov	ecx, 16
	call	??2@YAPEAX_K@Z				; operator new
	mov	rbx, rax
	test	rax, rax
	je	SHORT $LN4@OpenEventW
	mov	r8, rdi
	xor	edx, edx
	mov	ecx, 1048578				; 00100002H
	mov	QWORD PTR [rax], rdi
	call	QWORD PTR __imp_OpenEventA
	mov	QWORD PTR [rbx+8], rax
	jmp	SHORT $LN5@OpenEventW
$LN4@OpenEventW:
	xor	ebx, ebx
$LN5@OpenEventW:

; 54   : 
; 55   : 	if (handle->GetEventHandle() == nullptr) {

	cmp	QWORD PTR [rbx+8], 0
	jne	SHORT $LN1@OpenEventW

; 56   : 		delete (void *)handle;

	mov	rcx, rbx
	call	??3@YAXPEAX@Z				; operator delete

; 57   : 		return nullptr;

	xor	eax, eax

; 61   : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
$LN1@OpenEventW:

; 58   : 	}
; 59   : 
; 60   : 	return handle;

	mov	rax, rbx

; 61   : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
?OpenEventWaitHandle@@YAPEAVCEventWaitHandle@@PEAD@Z ENDP ; OpenEventWaitHandle
_TEXT	ENDS
PUBLIC	?Wait@CEventWaitHandle@@QEAAKXZ			; CEventWaitHandle::Wait
; Function compile flags: /Ogtpy
;	COMDAT ?Wait@CEventWaitHandle@@QEAAKXZ
_TEXT	SEGMENT
this$ = 8
?Wait@CEventWaitHandle@@QEAAKXZ PROC			; CEventWaitHandle::Wait, COMDAT

; 42   : 	return CEventWaitHandle::Wait(INFINITE);

	mov	rcx, QWORD PTR [rcx+8]
	or	edx, -1					; ffffffffH

; 43   : }

	rex_jmp	QWORD PTR __imp_WaitForSingleObject
?Wait@CEventWaitHandle@@QEAAKXZ ENDP			; CEventWaitHandle::Wait
END
