; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?getThreadLocalData@@YAPEAUThreadLocalData@@XZ	; getThreadLocalData
PUBLIC	??0IClassFactory@@QEAA@XZ			; IClassFactory::IClassFactory
PUBLIC	?AddRef@CProfilerFactory@@UEAAKXZ		; CProfilerFactory::AddRef
PUBLIC	?Release@CProfilerFactory@@UEAAKXZ		; CProfilerFactory::Release
PUBLIC	IsEqualGUID
PUBLIC	?QueryInterface@CProfilerFactory@@UEAAJAEBU_GUID@@PEAPEAX@Z ; CProfilerFactory::QueryInterface
PUBLIC	?CreateInstance@CProfilerFactory@@UEAAJPEAUIUnknown@@AEBU_GUID@@PEAPEAX@Z ; CProfilerFactory::CreateInstance
PUBLIC	?LockServer@CProfilerFactory@@UEAAJH@Z		; CProfilerFactory::LockServer
PUBLIC	??0CProfilerFactory@@QEAA@XZ			; CProfilerFactory::CProfilerFactory
PUBLIC	?tls_index@@3KA					; tls_index
PUBLIC	?g_cRefThisDll@@3JA				; g_cRefThisDll
PUBLIC	?g_module@@3PEAXEA				; g_module
PUBLIC	?allThreadLocalDatas@@3PEAVLightweightList@@EA	; allThreadLocalDatas
PUBLIC	??_7CProfilerFactory@@6B@			; CProfilerFactory::`vftable'
EXTRN	__imp_TlsAlloc:PROC
EXTRN	__imp_TlsSetValue:PROC
EXTRN	__imp_TlsGetValue:PROC
EXTRN	IID_IUnknown:BYTE
EXTRN	IID_IClassFactory:BYTE
?tls_index@@3KA DD 01H DUP (?)				; tls_index
?g_cRefThisDll@@3JA DD 01H DUP (?)			; g_cRefThisDll
?g_module@@3PEAXEA DQ 01H DUP (?)			; g_module
?allThreadLocalDatas@@3PEAVLightweightList@@EA DQ 01H DUP (?) ; allThreadLocalDatas
;	COMDAT ??_7CProfilerFactory@@6B@
CONST	SEGMENT
??_7CProfilerFactory@@6B@ DQ FLAT:?QueryInterface@CProfilerFactory@@UEAAJAEBU_GUID@@PEAPEAX@Z ; CProfilerFactory::`vftable'
	DQ	FLAT:?AddRef@CProfilerFactory@@UEAAKXZ
	DQ	FLAT:?Release@CProfilerFactory@@UEAAKXZ
	DQ	FLAT:?CreateInstance@CProfilerFactory@@UEAAJPEAUIUnknown@@AEBU_GUID@@PEAPEAX@Z
	DQ	FLAT:?LockServer@CProfilerFactory@@UEAAJH@Z
CLSID_Profiler DD 0e7e2c111H
	DW	03471H
	DW	04ac7H
	DB	0b2H
	DB	078H
	DB	011H
	DB	0f4H
	DB	0c2H
	DB	06eH
	DB	0dbH
	DB	0cfH
_bad_alloc_Message DQ FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
PUBLIC	DllCanUnloadNow
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\hook.cpp
;	COMDAT DllCanUnloadNow
_TEXT	SEGMENT
DllCanUnloadNow PROC					; COMDAT

; 85   :     return (g_cRefThisDll == 0 ? S_OK : S_FALSE);

	xor	eax, eax
	cmp	DWORD PTR ?g_cRefThisDll@@3JA, eax	; g_cRefThisDll
	setne	al

; 86   : }

	ret	0
DllCanUnloadNow ENDP
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\profilerfactory.h
_TEXT	ENDS
;	COMDAT ?LockServer@CProfilerFactory@@UEAAJH@Z
_TEXT	SEGMENT
this$ = 8
__formal$ = 16
?LockServer@CProfilerFactory@@UEAAJH@Z PROC		; CProfilerFactory::LockServer, COMDAT

; 46   : 	STDMETHODIMP LockServer(BOOL) {	return S_OK; }  // not implemented

	xor	eax, eax
	ret	0
?LockServer@CProfilerFactory@@UEAAJH@Z ENDP		; CProfilerFactory::LockServer
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?Release@CProfilerFactory@@UEAAKXZ
_TEXT	SEGMENT
this$ = 8
?Release@CProfilerFactory@@UEAAKXZ PROC			; CProfilerFactory::Release, COMDAT

; 24   : 		return 1; // Singleton

	mov	eax, 1

; 25   : 	}

	ret	0
?Release@CProfilerFactory@@UEAAKXZ ENDP			; CProfilerFactory::Release
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AddRef@CProfilerFactory@@UEAAKXZ
_TEXT	SEGMENT
this$ = 8
?AddRef@CProfilerFactory@@UEAAKXZ PROC			; CProfilerFactory::AddRef, COMDAT

; 19   : 		return 1; // Singleton

	mov	eax, 1

; 20   : 	}

	ret	0
?AddRef@CProfilerFactory@@UEAAKXZ ENDP			; CProfilerFactory::AddRef
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\global.h
_TEXT	ENDS
;	COMDAT ?getThreadLocalData@@YAPEAUThreadLocalData@@XZ
_TEXT	SEGMENT
?getThreadLocalData@@YAPEAUThreadLocalData@@XZ PROC	; getThreadLocalData, COMDAT

; 46   : 	return (ThreadLocalData*)TlsGetValue(tls_index);

	mov	ecx, DWORD PTR ?tls_index@@3KA		; tls_index

; 47   : }

	rex_jmp	QWORD PTR __imp_TlsGetValue
?getThreadLocalData@@YAPEAUThreadLocalData@@XZ ENDP	; getThreadLocalData
; Function compile flags: /Ogtpy
; File c:\program files\microsoft sdks\windows\v7.0\include\guiddef.h
_TEXT	ENDS
;	COMDAT IsEqualGUID
_TEXT	SEGMENT
rguid1$ = 8
rguid2$ = 16
IsEqualGUID PROC					; COMDAT

; 161  :     return !memcmp(&rguid1, &rguid2, sizeof(GUID));

	mov	rax, QWORD PTR [rcx]
	xor	r8d, r8d
	cmp	rax, QWORD PTR [rdx]
	jne	SHORT $LN3@IsEqualGUI
	mov	rax, QWORD PTR [rcx+8]
	cmp	rax, QWORD PTR [rdx+8]
	jne	SHORT $LN3@IsEqualGUI
	mov	eax, r8d
	test	eax, eax
	sete	r8b
	mov	eax, r8d

; 162  : }

	ret	0
$LN3@IsEqualGUI:

; 161  :     return !memcmp(&rguid1, &rguid2, sizeof(GUID));

	sbb	eax, eax
	sbb	eax, -1
	test	eax, eax
	sete	r8b
	mov	eax, r8d

; 162  : }

	ret	0
IsEqualGUID ENDP
; Function compile flags: /Ogtpy
;	COMDAT ??0IClassFactory@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0IClassFactory@@QEAA@XZ PROC				; IClassFactory::IClassFactory, COMDAT
	mov	rax, rcx
	ret	0
??0IClassFactory@@QEAA@XZ ENDP				; IClassFactory::IClassFactory
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ??0CProfilerFactory@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0CProfilerFactory@@QEAA@XZ PROC			; CProfilerFactory::CProfilerFactory, COMDAT
	lea	rax, OFFSET FLAT:??_7CProfilerFactory@@6B@
	mov	QWORD PTR [rcx], rax
	mov	rax, rcx
	ret	0
??0CProfilerFactory@@QEAA@XZ ENDP			; CProfilerFactory::CProfilerFactory
_TEXT	ENDS
PUBLIC	DllGetClassObject
;	COMDAT pdata
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\hook.cpp
pdata	SEGMENT
$pdata$DllGetClassObject DD imagerel $LN12
	DD	imagerel $LN12+146
	DD	imagerel $unwind$DllGetClassObject
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$DllGetClassObject DD 040a01H
	DD	06340aH
	DD	07006320aH
; Function compile flags: /Ogtpy
xdata	ENDS
;	COMDAT DllGetClassObject
_TEXT	SEGMENT
rclsid$ = 48
riid$ = 56
ppvOut$ = 64
DllGetClassObject PROC					; COMDAT

; 70   : {

$LN12:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H

; 71   : 	// MessageBox(nullptr, TEXT("DllGetClassObject"), TEXT("DllGetClassObject"), MB_OK);
; 72   : 
; 73   : 	*ppvOut = nullptr;

	mov	QWORD PTR [r8], 0

; 74   :     if (IsEqualIID(rclsid, CLSID_Profiler))

	mov	r9, QWORD PTR [rcx]
	lea	rax, OFFSET FLAT:CLSID_Profiler
	mov	rbx, r8
	mov	rdi, rdx
	cmp	r9, QWORD PTR [rax]
	jne	SHORT $LN10@DllGetClas
	mov	r9, QWORD PTR [rcx+8]
	cmp	r9, QWORD PTR [rax+8]
	jne	SHORT $LN10@DllGetClas
	xor	eax, eax
	jmp	SHORT $LN11@DllGetClas
$LN10@DllGetClas:
	sbb	eax, eax
	sbb	eax, -1
$LN11@DllGetClas:
	test	eax, eax
	jne	SHORT $LN1@DllGetClas

; 75   :     {
; 76   :        // declare a classfactory for CProfiler class 
; 77   :        CProfilerFactory *pcf = new CProfilerFactory;

	lea	ecx, QWORD PTR [rax+8]
	call	??2@YAPEAX_K@Z				; operator new
	mov	rcx, rax
	test	rax, rax
	je	SHORT $LN4@DllGetClas
	lea	rax, OFFSET FLAT:??_7CProfilerFactory@@6B@

; 78   :        return pcf->QueryInterface(riid,ppvOut);

	mov	r8, rbx
	mov	rdx, rdi
	mov	QWORD PTR [rcx], rax

; 81   : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	rex_jmp	QWORD PTR [rax]
$LN4@DllGetClas:

; 75   :     {
; 76   :        // declare a classfactory for CProfiler class 
; 77   :        CProfilerFactory *pcf = new CProfilerFactory;

	xor	ecx, ecx

; 78   :        return pcf->QueryInterface(riid,ppvOut);

	mov	r8, rbx
	mov	rdx, rdi
	mov	rax, QWORD PTR [rcx]

; 81   : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	rex_jmp	QWORD PTR [rax]
$LN1@DllGetClas:

; 79   :     }
; 80   :     return CLASS_E_CLASSNOTAVAILABLE;

	mov	eax, -2147221231			; ffffffff80040111H

; 81   : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
DllGetClassObject ENDP
_TEXT	ENDS
PUBLIC	DllMain
;	COMDAT pdata
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\lightweightstack.h
pdata	SEGMENT
$pdata$DllMain DD imagerel $LN29
	DD	imagerel $LN29+201
	DD	imagerel $unwind$DllMain
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$DllMain DD 010401H
	DD	04204H
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\hook.cpp
xdata	ENDS
;	COMDAT DllMain
_TEXT	SEGMENT
hModule$ = 48
ul_reason_for_call$ = 56
__formal$ = 64
DllMain	PROC						; COMDAT

; 33   : {

$LN29:
	sub	rsp, 40					; 00000028H

; 34   : 	switch (ul_reason_for_call)

	sub	edx, 1
	je	$LN5@DllMain
	sub	edx, 1
	je	SHORT $LN4@DllMain
	cmp	edx, 1
	jne	$LN27@DllMain

; 47   : 			//AttachToThread();
; 48   : 			break;
; 49   : 		}
; 50   : 
; 51   : 		case DLL_THREAD_DETACH: {
; 52   : 			DebugWriteLine(L"DLL_THREAD_DETACH");
; 53   : 			ThreadLocalData *data = getThreadLocalData();

	mov	ecx, DWORD PTR ?tls_index@@3KA		; tls_index
	call	QWORD PTR __imp_TlsGetValue
	mov	r11, rax

; 54   : 			DetachFromThread(data);

	test	rax, rax
	je	$LN27@DllMain
	rdtsc
	mov	rcx, QWORD PTR [r11+24]
	shl	rdx, 32					; 00000020H
	or	rax, rdx
	mov	r8, rax
	cmp	QWORD PTR [r11+32], rcx
	jb	SHORT $LN12@DllMain
	npad	7
$LL13@DllMain:
	mov	rcx, QWORD PTR [r11+32]
	mov	rax, r8
	sub	rax, QWORD PTR [rcx+8]
	mov	rdx, QWORD PTR [rcx]
	add	QWORD PTR [rdx+8], rax
	add	QWORD PTR [r11+32], -24
	mov	rax, QWORD PTR [r11+24]
	cmp	QWORD PTR [r11+32], rax
	jae	SHORT $LL13@DllMain
$LN12@DllMain:

; 55   : 			if (data != nullptr)
; 56   : 				allThreadLocalDatas->remove(data);

	mov	rcx, QWORD PTR ?allThreadLocalDatas@@3PEAVLightweightList@@EA ; allThreadLocalDatas
	mov	rdx, r11
	call	?remove@LightweightList@@QEAAXPEAUThreadLocalData@@@Z ; LightweightList::remove

; 57   : 			break;
; 58   : 		}
; 59   : 		
; 60   : 		case DLL_PROCESS_DETACH: {
; 61   : 			DebugWriteLine(L"DLL_PROCESS_DETACH");
; 62   : 			break;
; 63   : 		}
; 64   : 	}
; 65   : 
; 66   : 	return TRUE;

	mov	eax, 1

; 67   : }

	add	rsp, 40					; 00000028H
	ret	0
$LN4@DllMain:

; 41   : 			//AttachToThread();
; 42   : 			break;
; 43   : 
; 44   : 		case DLL_THREAD_ATTACH: {
; 45   : 			DebugWriteLine(L"DLL_THREAD_ATTACH");
; 46   : 			TlsSetValue(tls_index, nullptr);

	mov	ecx, DWORD PTR ?tls_index@@3KA		; tls_index
	xor	edx, edx
	call	QWORD PTR __imp_TlsSetValue

; 57   : 			break;
; 58   : 		}
; 59   : 		
; 60   : 		case DLL_PROCESS_DETACH: {
; 61   : 			DebugWriteLine(L"DLL_PROCESS_DETACH");
; 62   : 			break;
; 63   : 		}
; 64   : 	}
; 65   : 
; 66   : 	return TRUE;

	mov	eax, 1

; 67   : }

	add	rsp, 40					; 00000028H
	ret	0
$LN5@DllMain:

; 35   : 	{
; 36   : 		case DLL_PROCESS_ATTACH: 
; 37   : 			DebugWriteLine(L"DLL_PROCESS_ATTACH");
; 38   : 			g_module = hModule;

	mov	QWORD PTR ?g_module@@3PEAXEA, rcx	; g_module

; 39   : 			tls_index = TlsAlloc();

	call	QWORD PTR __imp_TlsAlloc

; 40   : 			TlsSetValue(tls_index, nullptr);

	xor	edx, edx
	mov	ecx, eax
	mov	DWORD PTR ?tls_index@@3KA, eax		; tls_index
	call	QWORD PTR __imp_TlsSetValue
$LN27@DllMain:

; 57   : 			break;
; 58   : 		}
; 59   : 		
; 60   : 		case DLL_PROCESS_DETACH: {
; 61   : 			DebugWriteLine(L"DLL_PROCESS_DETACH");
; 62   : 			break;
; 63   : 		}
; 64   : 	}
; 65   : 
; 66   : 	return TRUE;

	mov	eax, 1

; 67   : }

	add	rsp, 40					; 00000028H
	ret	0
DllMain	ENDP
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\profilerfactory.h
_TEXT	ENDS
;	COMDAT ?CreateInstance@CProfilerFactory@@UEAAJPEAUIUnknown@@AEBU_GUID@@PEAPEAX@Z
_TEXT	SEGMENT
this$ = 8
pUnkOuter$ = 16
riid$ = 24
ppvObj$ = 32
?CreateInstance@CProfilerFactory@@UEAAJPEAUIUnknown@@AEBU_GUID@@PEAPEAX@Z PROC ; CProfilerFactory::CreateInstance, COMDAT

; 38   : 	{

	mov	rax, r8

; 39   : 		*ppvObj = nullptr;

	mov	QWORD PTR [r9], 0

; 40   : 		if (pUnkOuter)

	test	rdx, rdx
	je	SHORT $LN1@CreateInst

; 41   :     		return CLASS_E_NOAGGREGATION;

	mov	eax, -2147221232			; ffffffff80040110H

; 43   : 		return hr;
; 44   : 	}

	ret	0
$LN1@CreateInst:

; 42   : 		HRESULT hr = profiler.QueryInterface(riid, ppvObj);

	lea	rcx, OFFSET FLAT:?profiler@@3VCProfiler@@A ; profiler
	mov	r8, r9
	mov	rdx, rax

; 43   : 		return hr;
; 44   : 	}

	jmp	?QueryInterface@CProfiler@@UEAAJAEBU_GUID@@PEAPEAX@Z ; CProfiler::QueryInterface
?CreateInstance@CProfilerFactory@@UEAAJPEAUIUnknown@@AEBU_GUID@@PEAPEAX@Z ENDP ; CProfilerFactory::CreateInstance
_TEXT	ENDS
;	COMDAT pdata
; File c:\program files\microsoft sdks\windows\v7.0\include\guiddef.h
pdata	SEGMENT
$pdata$?QueryInterface@CProfilerFactory@@UEAAJAEBU_GUID@@PEAPEAX@Z DD imagerel $LN13
	DD	imagerel $LN13+120
	DD	imagerel $unwind$?QueryInterface@CProfilerFactory@@UEAAJAEBU_GUID@@PEAPEAX@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?QueryInterface@CProfilerFactory@@UEAAJAEBU_GUID@@PEAPEAX@Z DD 020501H
	DD	013405H
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\profilerfactory.h
xdata	ENDS
;	COMDAT ?QueryInterface@CProfilerFactory@@UEAAJAEBU_GUID@@PEAPEAX@Z
_TEXT	SEGMENT
this$ = 8
riid$ = 16
ppv$ = 24
?QueryInterface@CProfilerFactory@@UEAAJAEBU_GUID@@PEAPEAX@Z PROC ; CProfilerFactory::QueryInterface, COMDAT

; 28   : 	{

$LN13:
	mov	QWORD PTR [rsp+8], rbx

; 29   : 		*ppv = nullptr;

	xor	r9d, r9d
	mov	rbx, rcx

; 30   : 		if(IsEqualIID(riid,IID_IUnknown) || IsEqualIID(riid,IID_IClassFactory)) {

	lea	rcx, OFFSET FLAT:__ImageBase
	mov	QWORD PTR [r8], r9
	mov	r11, QWORD PTR [rdx]
	cmp	r11, QWORD PTR IID_IUnknown[rcx]
	jne	SHORT $LN11@QueryInter@2
	mov	r11, QWORD PTR [rdx+8]
	cmp	r11, QWORD PTR IID_IUnknown[rcx+8]
	jne	SHORT $LN11@QueryInter@2
	mov	eax, r9d
	jmp	SHORT $LN12@QueryInter@2
$LN11@QueryInter@2:
	sbb	eax, eax
	sbb	eax, -1
$LN12@QueryInter@2:
	test	eax, eax
	je	SHORT $LN1@QueryInter@2
	lea	rax, QWORD PTR IID_IClassFactory[rcx]
	mov	rcx, QWORD PTR [rdx]
	cmp	rcx, QWORD PTR [rax]
	jne	SHORT $LN9@QueryInter@2
	mov	rcx, QWORD PTR [rdx+8]
	cmp	rcx, QWORD PTR [rax+8]
	je	SHORT $LN10@QueryInter@2
$LN9@QueryInter@2:
	sbb	eax, eax
	sbb	eax, -1
	mov	r9d, eax
$LN10@QueryInter@2:
	test	r9d, r9d
	je	SHORT $LN1@QueryInter@2

; 32   : 			return S_OK;
; 33   : 		}
; 34   : 		return E_NOINTERFACE;

	mov	eax, -2147467262			; ffffffff80004002H

; 35   : 	}

	mov	rbx, QWORD PTR [rsp+8]
	ret	0
$LN1@QueryInter@2:

; 31   : 			*ppv = this;

	mov	QWORD PTR [r8], rbx

; 35   : 	}

	mov	rbx, QWORD PTR [rsp+8]
	xor	eax, eax
	ret	0
?QueryInterface@CProfilerFactory@@UEAAJAEBU_GUID@@PEAPEAX@Z ENDP ; CProfilerFactory::QueryInterface
PUBLIC	?AttachToThread@@YAPEAUThreadLocalData@@XZ	; AttachToThread
;	COMDAT pdata
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\hook.cpp
pdata	SEGMENT
$pdata$?AttachToThread@@YAPEAUThreadLocalData@@XZ DD imagerel $LN3
	DD	imagerel $LN3+45
	DD	imagerel $unwind$?AttachToThread@@YAPEAUThreadLocalData@@XZ
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?AttachToThread@@YAPEAUThreadLocalData@@XZ DD 020601H
	DD	030023206H
; Function compile flags: /Ogtpy
xdata	ENDS
;	COMDAT ?AttachToThread@@YAPEAUThreadLocalData@@XZ
_TEXT	SEGMENT
?AttachToThread@@YAPEAUThreadLocalData@@XZ PROC		; AttachToThread, COMDAT

; 23   : {

$LN3:
	push	rbx
	sub	rsp, 32					; 00000020H

; 24   : 	ThreadLocalData *data = allThreadLocalDatas->add();

	mov	rcx, QWORD PTR ?allThreadLocalDatas@@3PEAVLightweightList@@EA ; allThreadLocalDatas
	call	?add@LightweightList@@QEAAPEAUThreadLocalData@@XZ ; LightweightList::add

; 25   : 	TlsSetValue(tls_index, data);

	mov	ecx, DWORD PTR ?tls_index@@3KA		; tls_index
	mov	rdx, rax
	mov	rbx, rax
	call	QWORD PTR __imp_TlsSetValue

; 26   : 	return data;

	mov	rax, rbx

; 27   : }

	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
?AttachToThread@@YAPEAUThreadLocalData@@XZ ENDP		; AttachToThread
END
