; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0DL@FKOGONME@Could?5not?5open?5Shared?5Memory?0?5pl@ ; `string'
PUBLIC	??_C@_0CL@JNLEPBOA@Wrong?5build?5configuration?$DL?5RELEA@ ; `string'
PUBLIC	??_C@_0EI@IBFBEDOB@Error?5while?5creating?5temporary?5s@ ; `string'
EXTRN	__imp_MapViewOfFile:PROC
EXTRN	__imp_UnmapViewOfFile:PROC
EXTRN	__imp_OpenFileMappingA:PROC
EXTRN	__imp_CloseHandle:PROC
;	COMDAT ??_C@_0EI@IBFBEDOB@Error?5while?5creating?5temporary?5s@
CONST	SEGMENT
??_C@_0EI@IBFBEDOB@Error?5while?5creating?5temporary?5s@ DB 'Error while '
	DB	'creating temporary storage file (shared memory)!', 0aH, 0aH, 'E'
	DB	'rror: %d', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0CL@JNLEPBOA@Wrong?5build?5configuration?$DL?5RELEA@
CONST	SEGMENT
??_C@_0CL@JNLEPBOA@Wrong?5build?5configuration?$DL?5RELEA@ DB 'Wrong buil'
	DB	'd configuration; RELEASE needed!', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0DL@FKOGONME@Could?5not?5open?5Shared?5Memory?0?5pl@
CONST	SEGMENT
??_C@_0DL@FKOGONME@Could?5not?5open?5Shared?5Memory?0?5pl@ DB 'Could not '
	DB	'open Shared Memory, please restart the profiler!', 00H ; `string'
_bad_alloc_Message DQ FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
PUBLIC	?GetStartPtr@CSharedMemory@@QEAAPEAXXZ		; CSharedMemory::GetStartPtr
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\sharedmemory.cpp
;	COMDAT ?GetStartPtr@CSharedMemory@@QEAAPEAXXZ
_TEXT	SEGMENT
this$ = 8
?GetStartPtr@CSharedMemory@@QEAAPEAXXZ PROC		; CSharedMemory::GetStartPtr, COMDAT

; 59   : 	return this->startPtr;

	mov	rax, QWORD PTR [rcx+16]

; 60   : }

	ret	0
?GetStartPtr@CSharedMemory@@QEAAPEAXXZ ENDP		; CSharedMemory::GetStartPtr
_TEXT	ENDS
PUBLIC	??0CSharedMemory@@QEAA@PEAD@Z			; CSharedMemory::CSharedMemory
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0CSharedMemory@@QEAA@PEAD@Z DD imagerel $LN8
	DD	imagerel $LN8+281
	DD	imagerel $unwind$??0CSharedMemory@@QEAA@PEAD@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0CSharedMemory@@QEAA@PEAD@Z DD 050d01H
	DD	048340dH
	DD	046010dH
	DD	07006H
; Function compile flags: /Ogtpy
xdata	ENDS
;	COMDAT ??0CSharedMemory@@QEAA@PEAD@Z
_TEXT	SEGMENT
buffer$80452 = 48
this$ = 576
name$ = 584
??0CSharedMemory@@QEAA@PEAD@Z PROC			; CSharedMemory::CSharedMemory, COMDAT

; 12   : {

$LN8:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 560				; 00000230H
	mov	rbx, rcx

; 13   : 	this->fileHandle = OpenFileMapping(FILE_MAP_ALL_ACCESS, false, name);

	mov	r8, rdx
	xor	edx, edx
	mov	ecx, 983071				; 000f001fH
	call	QWORD PTR __imp_OpenFileMappingA

; 14   : 	if (fileHandle == nullptr) {
; 15   : 		DebugWriteLine(L"OpenFileMapping returned nullptr");
; 16   : 	}
; 17   : 	this->startPtr = MapViewOfFile(this->fileHandle, FILE_MAP_ALL_ACCESS, 0, 0, sizeof(SharedMemoryHeader));

	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 983071				; 000f001fH
	mov	rcx, rax
	mov	QWORD PTR [rsp+32], 344			; 00000158H
	mov	QWORD PTR [rbx+8], rax
	call	QWORD PTR __imp_MapViewOfFile
	mov	QWORD PTR [rbx+16], rax

; 18   : 	if (startPtr == nullptr) {

	test	rax, rax
	jne	SHORT $LN4@CSharedMem

; 19   : 		DebugWriteLine(L"MapViewOfFile returned nullptr");
; 20   : 		MessageBox(nullptr, TEXT("Could not open Shared Memory, please restart the profiler!"), TEXT("Profiler Error"), MB_OK);

	lea	r8, OFFSET FLAT:??_C@_0P@NHBFFJJG@Profiler?5Error?$AA@
	lea	rdx, OFFSET FLAT:??_C@_0DL@FKOGONME@Could?5not?5open?5Shared?5Memory?0?5pl@
	xor	r9d, r9d
	xor	ecx, ecx
	call	QWORD PTR __imp_MessageBoxA
$LN4@CSharedMem:

; 21   : 	}
; 22   : 	SharedMemoryHeader *header = (SharedMemoryHeader*)this->startPtr;

	mov	rdi, QWORD PTR [rbx+16]

; 23   : 	#ifdef DEBUG
; 24   : 	if (header->Magic != '~DBG') {
; 25   : 		DebugWriteLine(L"Corrupted shared memory header");
; 26   : 		if (header->Magic == '~SM1') {
; 27   : 			MessageBox(nullptr, TEXT("Wrong build configuration; DEBUG needed!"), TEXT("Profiler Error"), MB_OK);
; 28   : 		}
; 29   : 	}
; 30   : 	#else
; 31   : 	if (header->Magic != '~SM1') {

	mov	eax, DWORD PTR [rdi]
	cmp	eax, 2119388465				; 7e534d31H
	je	SHORT $LN2@CSharedMem

; 32   : 		DebugWriteLine(L"Corrupted shared memory header");
; 33   : 		if (header->Magic == '~DBG') {

	cmp	eax, 2118402631				; 7e444247H
	jne	SHORT $LN2@CSharedMem

; 34   : 			MessageBox(nullptr, TEXT("Wrong build configuration; RELEASE needed!"), TEXT("Profiler Error"), MB_OK);

	lea	r8, OFFSET FLAT:??_C@_0P@NHBFFJJG@Profiler?5Error?$AA@
	lea	rdx, OFFSET FLAT:??_C@_0CL@JNLEPBOA@Wrong?5build?5configuration?$DL?5RELEA@
	xor	r9d, r9d
	xor	ecx, ecx
	call	QWORD PTR __imp_MessageBoxA
$LN2@CSharedMem:

; 35   : 		}
; 36   : 	}
; 37   : 	#endif
; 38   : 	this->length = header->TotalLength;

	mov	eax, DWORD PTR [rdi+8]

; 39   : 	UnmapViewOfFile(this->startPtr);

	mov	rcx, QWORD PTR [rbx+16]
	mov	DWORD PTR [rbx+24], eax
	call	QWORD PTR __imp_UnmapViewOfFile

; 40   : 	DebugWriteLine(L"Length: %d", this->length);
; 41   : 	this->startPtr = MapViewOfFile(this->fileHandle, FILE_MAP_ALL_ACCESS, 0, 0, this->length);

	movsxd	r11, DWORD PTR [rbx+24]
	mov	rcx, QWORD PTR [rbx+8]
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 983071				; 000f001fH
	mov	QWORD PTR [rsp+32], r11
	call	QWORD PTR __imp_MapViewOfFile
	mov	QWORD PTR [rbx+16], rax

; 42   : 	if (startPtr == nullptr) {

	test	rax, rax
	jne	SHORT $LN1@CSharedMem

; 43   : 		char buffer[512];
; 44   : 		sprintf_s(buffer, 512, "Error while creating temporary storage file (shared memory)!\n\nError: %d", GetLastError());

	call	QWORD PTR __imp_GetLastError
	lea	r8, OFFSET FLAT:??_C@_0EI@IBFBEDOB@Error?5while?5creating?5temporary?5s@
	lea	rcx, QWORD PTR buffer$80452[rsp]
	mov	r9d, eax
	mov	edx, 512				; 00000200H
	call	QWORD PTR __imp_sprintf_s

; 45   : 		DebugWriteLine(L"second MapViewOfFile returned nullptr");
; 46   : 		MessageBox(nullptr, buffer, TEXT("Profiler Error"), MB_OK);

	lea	r8, OFFSET FLAT:??_C@_0P@NHBFFJJG@Profiler?5Error?$AA@
	lea	rdx, QWORD PTR buffer$80452[rsp]
	xor	r9d, r9d
	xor	ecx, ecx
	call	QWORD PTR __imp_MessageBoxA
$LN1@CSharedMem:

; 47   : 	}
; 48   : 	this->header = (SharedMemoryHeader*)this->startPtr;

	mov	rax, QWORD PTR [rbx+16]
	mov	QWORD PTR [rbx], rax

; 49   : }

	mov	rax, rbx
	mov	rbx, QWORD PTR [rsp+576]
	add	rsp, 560				; 00000230H
	pop	rdi
	ret	0
??0CSharedMemory@@QEAA@PEAD@Z ENDP			; CSharedMemory::CSharedMemory
END
