; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Local\SharpDevelop_3.2.0.5777_Source\src\AddIns\Misc\Profiler\Hook\CorProfilerCallbackImpl.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	?HandleDestroyed@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::HandleDestroyed
PUBLIC	?HandleCreated@CCorProfilerCallbackImpl@@UAGJII@Z ; CCorProfilerCallbackImpl::HandleCreated
PUBLIC	?RootReferences2@CCorProfilerCallbackImpl@@UAGJKQAIQAW4__MIDL___MIDL_itf_corprof_0011_0001@@QAW4__MIDL___MIDL_itf_corprof_0011_0002@@0@Z ; CCorProfilerCallbackImpl::RootReferences2
PUBLIC	?FinalizeableObjectQueued@CCorProfilerCallbackImpl@@UAGJKI@Z ; CCorProfilerCallbackImpl::FinalizeableObjectQueued
PUBLIC	?GarbageCollectionFinished@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::GarbageCollectionFinished
PUBLIC	?SurvivingReferences@CCorProfilerCallbackImpl@@UAGJKQAIQAK@Z ; CCorProfilerCallbackImpl::SurvivingReferences
PUBLIC	?GarbageCollectionStarted@CCorProfilerCallbackImpl@@UAGJHQAHW4__MIDL___MIDL_itf_corprof_0011_0006@@@Z ; CCorProfilerCallbackImpl::GarbageCollectionStarted
PUBLIC	?ThreadNameChanged@CCorProfilerCallbackImpl@@UAGJIKQA_W@Z ; CCorProfilerCallbackImpl::ThreadNameChanged
PUBLIC	?ExceptionCLRCatcherExecute@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::ExceptionCLRCatcherExecute
PUBLIC	?ExceptionCLRCatcherFound@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::ExceptionCLRCatcherFound
PUBLIC	?COMClassicVTableDestroyed@CCorProfilerCallbackImpl@@UAGJIABU_GUID@@PAX@Z ; CCorProfilerCallbackImpl::COMClassicVTableDestroyed
PUBLIC	?COMClassicVTableCreated@CCorProfilerCallbackImpl@@UAGJIABU_GUID@@PAXK@Z ; CCorProfilerCallbackImpl::COMClassicVTableCreated
PUBLIC	?ExceptionCatcherLeave@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::ExceptionCatcherLeave
PUBLIC	?ExceptionCatcherEnter@CCorProfilerCallbackImpl@@UAGJII@Z ; CCorProfilerCallbackImpl::ExceptionCatcherEnter
PUBLIC	?ExceptionUnwindFinallyLeave@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyLeave
PUBLIC	?ExceptionUnwindFinallyEnter@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyEnter
PUBLIC	?ExceptionUnwindFunctionLeave@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionLeave
PUBLIC	?ExceptionUnwindFunctionEnter@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionEnter
PUBLIC	?ExceptionOSHandlerLeave@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ExceptionOSHandlerLeave
PUBLIC	?ExceptionOSHandlerEnter@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ExceptionOSHandlerEnter
PUBLIC	?ExceptionSearchCatcherFound@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ExceptionSearchCatcherFound
PUBLIC	?ExceptionSearchFilterLeave@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::ExceptionSearchFilterLeave
PUBLIC	?ExceptionSearchFilterEnter@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ExceptionSearchFilterEnter
PUBLIC	?ExceptionSearchFunctionLeave@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::ExceptionSearchFunctionLeave
PUBLIC	?ExceptionSearchFunctionEnter@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ExceptionSearchFunctionEnter
PUBLIC	?ExceptionThrown@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ExceptionThrown
PUBLIC	?RootReferences@CCorProfilerCallbackImpl@@UAGJKQAI@Z ; CCorProfilerCallbackImpl::RootReferences
PUBLIC	?ObjectReferences@CCorProfilerCallbackImpl@@UAGJIIKQAI@Z ; CCorProfilerCallbackImpl::ObjectReferences
PUBLIC	?ObjectsAllocatedByClass@CCorProfilerCallbackImpl@@UAGJKQAIQAK@Z ; CCorProfilerCallbackImpl::ObjectsAllocatedByClass
PUBLIC	?ObjectAllocated@CCorProfilerCallbackImpl@@UAGJII@Z ; CCorProfilerCallbackImpl::ObjectAllocated
PUBLIC	?MovedReferences@CCorProfilerCallbackImpl@@UAGJKQAI0QAK@Z ; CCorProfilerCallbackImpl::MovedReferences
PUBLIC	?RuntimeThreadResumed@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::RuntimeThreadResumed
PUBLIC	?RuntimeThreadSuspended@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::RuntimeThreadSuspended
PUBLIC	?RuntimeResumeFinished@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::RuntimeResumeFinished
PUBLIC	?RuntimeResumeStarted@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::RuntimeResumeStarted
PUBLIC	?RuntimeSuspendAborted@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::RuntimeSuspendAborted
PUBLIC	?RuntimeSuspendFinished@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::RuntimeSuspendFinished
PUBLIC	?RuntimeSuspendStarted@CCorProfilerCallbackImpl@@UAGJW4__MIDL___MIDL_itf_corprof_0000_0006@@@Z ; CCorProfilerCallbackImpl::RuntimeSuspendStarted
PUBLIC	?ManagedToUnmanagedTransition@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z ; CCorProfilerCallbackImpl::ManagedToUnmanagedTransition
PUBLIC	?UnmanagedToManagedTransition@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z ; CCorProfilerCallbackImpl::UnmanagedToManagedTransition
PUBLIC	?RemotingServerSendingReply@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z ; CCorProfilerCallbackImpl::RemotingServerSendingReply
PUBLIC	?RemotingServerInvocationReturned@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::RemotingServerInvocationReturned
PUBLIC	?RemotingServerInvocationStarted@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::RemotingServerInvocationStarted
PUBLIC	?RemotingServerReceivingMessage@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z ; CCorProfilerCallbackImpl::RemotingServerReceivingMessage
PUBLIC	?RemotingClientInvocationFinished@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::RemotingClientInvocationFinished
PUBLIC	?RemotingClientReceivingReply@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z ; CCorProfilerCallbackImpl::RemotingClientReceivingReply
PUBLIC	?RemotingClientSendingMessage@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z ; CCorProfilerCallbackImpl::RemotingClientSendingMessage
PUBLIC	?RemotingClientInvocationStarted@CCorProfilerCallbackImpl@@UAGJXZ ; CCorProfilerCallbackImpl::RemotingClientInvocationStarted
PUBLIC	?ThreadAssignedToOSThread@CCorProfilerCallbackImpl@@UAGJIK@Z ; CCorProfilerCallbackImpl::ThreadAssignedToOSThread
PUBLIC	?ThreadDestroyed@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ThreadDestroyed
PUBLIC	?ThreadCreated@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ThreadCreated
PUBLIC	?JITInlining@CCorProfilerCallbackImpl@@UAGJIIPAH@Z ; CCorProfilerCallbackImpl::JITInlining
PUBLIC	?JITFunctionPitched@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::JITFunctionPitched
PUBLIC	?JITCachedFunctionSearchFinished@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0004@@@Z ; CCorProfilerCallbackImpl::JITCachedFunctionSearchFinished
PUBLIC	?JITCachedFunctionSearchStarted@CCorProfilerCallbackImpl@@UAGJIPAH@Z ; CCorProfilerCallbackImpl::JITCachedFunctionSearchStarted
PUBLIC	?JITCompilationFinished@CCorProfilerCallbackImpl@@UAGJIJH@Z ; CCorProfilerCallbackImpl::JITCompilationFinished
PUBLIC	?JITCompilationStarted@CCorProfilerCallbackImpl@@UAGJIH@Z ; CCorProfilerCallbackImpl::JITCompilationStarted
PUBLIC	?FunctionUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::FunctionUnloadStarted
PUBLIC	?ClassUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ; CCorProfilerCallbackImpl::ClassUnloadFinished
PUBLIC	?ClassUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ClassUnloadStarted
PUBLIC	?ClassLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ; CCorProfilerCallbackImpl::ClassLoadFinished
PUBLIC	?ClassLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ClassLoadStarted
PUBLIC	?ModuleAttachedToAssembly@CCorProfilerCallbackImpl@@UAGJII@Z ; CCorProfilerCallbackImpl::ModuleAttachedToAssembly
PUBLIC	?ModuleUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ; CCorProfilerCallbackImpl::ModuleUnloadFinished
PUBLIC	?ModuleUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ModuleUnloadStarted
PUBLIC	?ModuleLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ; CCorProfilerCallbackImpl::ModuleLoadFinished
PUBLIC	?ModuleLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::ModuleLoadStarted
PUBLIC	?AssemblyUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ; CCorProfilerCallbackImpl::AssemblyUnloadFinished
PUBLIC	?AssemblyUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::AssemblyUnloadStarted
PUBLIC	?AssemblyLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ; CCorProfilerCallbackImpl::AssemblyLoadFinished
PUBLIC	?AssemblyLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::AssemblyLoadStarted
PUBLIC	?AppDomainShutdownFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ; CCorProfilerCallbackImpl::AppDomainShutdownFinished
PUBLIC	?AppDomainShutdownStarted@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::AppDomainShutdownStarted
PUBLIC	?AppDomainCreationFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ; CCorProfilerCallbackImpl::AppDomainCreationFinished
PUBLIC	?AppDomainCreationStarted@CCorProfilerCallbackImpl@@UAGJI@Z ; CCorProfilerCallbackImpl::AppDomainCreationStarted
PUBLIC	?Shutdown@CCorProfilerCallbackImpl@@UAGJXZ	; CCorProfilerCallbackImpl::Shutdown
PUBLIC	?Initialize@CCorProfilerCallbackImpl@@UAGJPAUIUnknown@@@Z ; CCorProfilerCallbackImpl::Initialize
PUBLIC	??0IUnknown@@QAE@XZ				; IUnknown::IUnknown
PUBLIC	??0ICorProfilerCallback@@QAE@XZ			; ICorProfilerCallback::ICorProfilerCallback
PUBLIC	??0ICorProfilerCallback2@@QAE@XZ		; ICorProfilerCallback2::ICorProfilerCallback2
PUBLIC	??_7CCorProfilerCallbackImpl@@6B@		; CCorProfilerCallbackImpl::`vftable'
EXTRN	__purecall:PROC
;	COMDAT ??_7CCorProfilerCallbackImpl@@6B@
CONST	SEGMENT
??_7CCorProfilerCallbackImpl@@6B@ DD FLAT:__purecall	; CCorProfilerCallbackImpl::`vftable'
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:?Initialize@CCorProfilerCallbackImpl@@UAGJPAUIUnknown@@@Z
	DD	FLAT:?Shutdown@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?AppDomainCreationStarted@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?AppDomainCreationFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
	DD	FLAT:?AppDomainShutdownStarted@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?AppDomainShutdownFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
	DD	FLAT:?AssemblyLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?AssemblyLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
	DD	FLAT:?AssemblyUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?AssemblyUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
	DD	FLAT:?ModuleLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ModuleLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
	DD	FLAT:?ModuleUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ModuleUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
	DD	FLAT:?ModuleAttachedToAssembly@CCorProfilerCallbackImpl@@UAGJII@Z
	DD	FLAT:?ClassLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ClassLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
	DD	FLAT:?ClassUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ClassUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
	DD	FLAT:?FunctionUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?JITCompilationStarted@CCorProfilerCallbackImpl@@UAGJIH@Z
	DD	FLAT:?JITCompilationFinished@CCorProfilerCallbackImpl@@UAGJIJH@Z
	DD	FLAT:?JITCachedFunctionSearchStarted@CCorProfilerCallbackImpl@@UAGJIPAH@Z
	DD	FLAT:?JITCachedFunctionSearchFinished@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0004@@@Z
	DD	FLAT:?JITFunctionPitched@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?JITInlining@CCorProfilerCallbackImpl@@UAGJIIPAH@Z
	DD	FLAT:?ThreadCreated@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ThreadDestroyed@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ThreadAssignedToOSThread@CCorProfilerCallbackImpl@@UAGJIK@Z
	DD	FLAT:?RemotingClientInvocationStarted@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?RemotingClientSendingMessage@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z
	DD	FLAT:?RemotingClientReceivingReply@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z
	DD	FLAT:?RemotingClientInvocationFinished@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?RemotingServerReceivingMessage@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z
	DD	FLAT:?RemotingServerInvocationStarted@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?RemotingServerInvocationReturned@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?RemotingServerSendingReply@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z
	DD	FLAT:?UnmanagedToManagedTransition@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z
	DD	FLAT:?ManagedToUnmanagedTransition@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z
	DD	FLAT:?RuntimeSuspendStarted@CCorProfilerCallbackImpl@@UAGJW4__MIDL___MIDL_itf_corprof_0000_0006@@@Z
	DD	FLAT:?RuntimeSuspendFinished@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?RuntimeSuspendAborted@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?RuntimeResumeStarted@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?RuntimeResumeFinished@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?RuntimeThreadSuspended@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?RuntimeThreadResumed@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?MovedReferences@CCorProfilerCallbackImpl@@UAGJKQAI0QAK@Z
	DD	FLAT:?ObjectAllocated@CCorProfilerCallbackImpl@@UAGJII@Z
	DD	FLAT:?ObjectsAllocatedByClass@CCorProfilerCallbackImpl@@UAGJKQAIQAK@Z
	DD	FLAT:?ObjectReferences@CCorProfilerCallbackImpl@@UAGJIIKQAI@Z
	DD	FLAT:?RootReferences@CCorProfilerCallbackImpl@@UAGJKQAI@Z
	DD	FLAT:?ExceptionThrown@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ExceptionSearchFunctionEnter@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ExceptionSearchFunctionLeave@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?ExceptionSearchFilterEnter@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ExceptionSearchFilterLeave@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?ExceptionSearchCatcherFound@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ExceptionOSHandlerEnter@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ExceptionOSHandlerLeave@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ExceptionUnwindFunctionEnter@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ExceptionUnwindFunctionLeave@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?ExceptionUnwindFinallyEnter@CCorProfilerCallbackImpl@@UAGJI@Z
	DD	FLAT:?ExceptionUnwindFinallyLeave@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?ExceptionCatcherEnter@CCorProfilerCallbackImpl@@UAGJII@Z
	DD	FLAT:?ExceptionCatcherLeave@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?COMClassicVTableCreated@CCorProfilerCallbackImpl@@UAGJIABU_GUID@@PAXK@Z
	DD	FLAT:?COMClassicVTableDestroyed@CCorProfilerCallbackImpl@@UAGJIABU_GUID@@PAX@Z
	DD	FLAT:?ExceptionCLRCatcherFound@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?ExceptionCLRCatcherExecute@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?ThreadNameChanged@CCorProfilerCallbackImpl@@UAGJIKQA_W@Z
	DD	FLAT:?GarbageCollectionStarted@CCorProfilerCallbackImpl@@UAGJHQAHW4__MIDL___MIDL_itf_corprof_0011_0006@@@Z
	DD	FLAT:?SurvivingReferences@CCorProfilerCallbackImpl@@UAGJKQAIQAK@Z
	DD	FLAT:?GarbageCollectionFinished@CCorProfilerCallbackImpl@@UAGJXZ
	DD	FLAT:?FinalizeableObjectQueued@CCorProfilerCallbackImpl@@UAGJKI@Z
	DD	FLAT:?RootReferences2@CCorProfilerCallbackImpl@@UAGJKQAIQAW4__MIDL___MIDL_itf_corprof_0011_0001@@QAW4__MIDL___MIDL_itf_corprof_0011_0002@@0@Z
	DD	FLAT:?HandleCreated@CCorProfilerCallbackImpl@@UAGJII@Z
	DD	FLAT:?HandleDestroyed@CCorProfilerCallbackImpl@@UAGJI@Z
__bad_alloc_Message DD FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\corprofilercallbackimpl.cpp
;	COMDAT ?HandleDestroyed@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_handleID$ = 12						; size = 4
?HandleDestroyed@CCorProfilerCallbackImpl@@UAGJI@Z PROC	; CCorProfilerCallbackImpl::HandleDestroyed, COMDAT

; 408  :     return S_OK;

	xor	eax, eax

; 409  : }

	ret	8
?HandleDestroyed@CCorProfilerCallbackImpl@@UAGJI@Z ENDP	; CCorProfilerCallbackImpl::HandleDestroyed
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?HandleCreated@CCorProfilerCallbackImpl@@UAGJII@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_handleID$ = 12						; size = 4
_initialObjectID$ = 16					; size = 4
?HandleCreated@CCorProfilerCallbackImpl@@UAGJII@Z PROC	; CCorProfilerCallbackImpl::HandleCreated, COMDAT

; 403  :     return S_OK;

	xor	eax, eax

; 404  : }

	ret	12					; 0000000cH
?HandleCreated@CCorProfilerCallbackImpl@@UAGJII@Z ENDP	; CCorProfilerCallbackImpl::HandleCreated
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RootReferences2@CCorProfilerCallbackImpl@@UAGJKQAIQAW4__MIDL___MIDL_itf_corprof_0011_0001@@QAW4__MIDL___MIDL_itf_corprof_0011_0002@@0@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_cRootRefs$ = 12					; size = 4
_rootRefIDs$ = 16					; size = 4
_rootKinds$ = 20					; size = 4
_rootFlags$ = 24					; size = 4
_rootIDs$ = 28						; size = 4
?RootReferences2@CCorProfilerCallbackImpl@@UAGJKQAIQAW4__MIDL___MIDL_itf_corprof_0011_0001@@QAW4__MIDL___MIDL_itf_corprof_0011_0002@@0@Z PROC ; CCorProfilerCallbackImpl::RootReferences2, COMDAT

; 398  :     return S_OK;

	xor	eax, eax

; 399  : }

	ret	24					; 00000018H
?RootReferences2@CCorProfilerCallbackImpl@@UAGJKQAIQAW4__MIDL___MIDL_itf_corprof_0011_0001@@QAW4__MIDL___MIDL_itf_corprof_0011_0002@@0@Z ENDP ; CCorProfilerCallbackImpl::RootReferences2
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?FinalizeableObjectQueued@CCorProfilerCallbackImpl@@UAGJKI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_finalizerFlags$ = 12					; size = 4
_objectID$ = 16						; size = 4
?FinalizeableObjectQueued@CCorProfilerCallbackImpl@@UAGJKI@Z PROC ; CCorProfilerCallbackImpl::FinalizeableObjectQueued, COMDAT

; 393  :     return S_OK;

	xor	eax, eax

; 394  : }

	ret	12					; 0000000cH
?FinalizeableObjectQueued@CCorProfilerCallbackImpl@@UAGJKI@Z ENDP ; CCorProfilerCallbackImpl::FinalizeableObjectQueued
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GarbageCollectionFinished@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GarbageCollectionFinished@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::GarbageCollectionFinished, COMDAT

; 388  :     return S_OK;

	xor	eax, eax

; 389  : }

	ret	4
?GarbageCollectionFinished@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::GarbageCollectionFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?SurvivingReferences@CCorProfilerCallbackImpl@@UAGJKQAIQAK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_cSurvivingObjectIDRanges$ = 12				; size = 4
_objectIDRangeStart$ = 16				; size = 4
_cObjectIDRangeLength$ = 20				; size = 4
?SurvivingReferences@CCorProfilerCallbackImpl@@UAGJKQAIQAK@Z PROC ; CCorProfilerCallbackImpl::SurvivingReferences, COMDAT

; 383  :     return S_OK;

	xor	eax, eax

; 384  : }

	ret	16					; 00000010H
?SurvivingReferences@CCorProfilerCallbackImpl@@UAGJKQAIQAK@Z ENDP ; CCorProfilerCallbackImpl::SurvivingReferences
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GarbageCollectionStarted@CCorProfilerCallbackImpl@@UAGJHQAHW4__MIDL___MIDL_itf_corprof_0011_0006@@@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_cGenerations$ = 12					; size = 4
_generationCollected$ = 16				; size = 4
_reason$ = 20						; size = 4
?GarbageCollectionStarted@CCorProfilerCallbackImpl@@UAGJHQAHW4__MIDL___MIDL_itf_corprof_0011_0006@@@Z PROC ; CCorProfilerCallbackImpl::GarbageCollectionStarted, COMDAT

; 378  : 	return S_OK;

	xor	eax, eax

; 379  : }

	ret	16					; 00000010H
?GarbageCollectionStarted@CCorProfilerCallbackImpl@@UAGJHQAHW4__MIDL___MIDL_itf_corprof_0011_0006@@@Z ENDP ; CCorProfilerCallbackImpl::GarbageCollectionStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ThreadNameChanged@CCorProfilerCallbackImpl@@UAGJIKQA_W@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_threadID$ = 12						; size = 4
_cchName$ = 16						; size = 4
_name$ = 20						; size = 4
?ThreadNameChanged@CCorProfilerCallbackImpl@@UAGJIKQA_W@Z PROC ; CCorProfilerCallbackImpl::ThreadNameChanged, COMDAT

; 373  : 	return S_OK;

	xor	eax, eax

; 374  : }

	ret	16					; 00000010H
?ThreadNameChanged@CCorProfilerCallbackImpl@@UAGJIKQA_W@Z ENDP ; CCorProfilerCallbackImpl::ThreadNameChanged
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?COMClassicVTableDestroyed@CCorProfilerCallbackImpl@@UAGJIABU_GUID@@PAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_wrappedClassID$ = 12					; size = 4
_implementedIID$ = 16					; size = 4
_pVTable$ = 20						; size = 4
?COMClassicVTableDestroyed@CCorProfilerCallbackImpl@@UAGJIABU_GUID@@PAX@Z PROC ; CCorProfilerCallbackImpl::COMClassicVTableDestroyed, COMDAT

; 368  :     return S_OK;

	xor	eax, eax

; 369  : }

	ret	16					; 00000010H
?COMClassicVTableDestroyed@CCorProfilerCallbackImpl@@UAGJIABU_GUID@@PAX@Z ENDP ; CCorProfilerCallbackImpl::COMClassicVTableDestroyed
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?COMClassicVTableCreated@CCorProfilerCallbackImpl@@UAGJIABU_GUID@@PAXK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_wrappedClassID$ = 12					; size = 4
_implementedIID$ = 16					; size = 4
_pVTable$ = 20						; size = 4
_cSlots$ = 24						; size = 4
?COMClassicVTableCreated@CCorProfilerCallbackImpl@@UAGJIABU_GUID@@PAXK@Z PROC ; CCorProfilerCallbackImpl::COMClassicVTableCreated, COMDAT

; 363  :     return S_OK;

	xor	eax, eax

; 364  : }

	ret	20					; 00000014H
?COMClassicVTableCreated@CCorProfilerCallbackImpl@@UAGJIABU_GUID@@PAXK@Z ENDP ; CCorProfilerCallbackImpl::COMClassicVTableCreated
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionCatcherLeave@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?ExceptionCatcherLeave@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::ExceptionCatcherLeave, COMDAT

; 358  :     return S_OK;

	xor	eax, eax

; 359  : }

	ret	4
?ExceptionCatcherLeave@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionCatcherLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionCatcherEnter@CCorProfilerCallbackImpl@@UAGJII@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
_objectID$ = 16						; size = 4
?ExceptionCatcherEnter@CCorProfilerCallbackImpl@@UAGJII@Z PROC ; CCorProfilerCallbackImpl::ExceptionCatcherEnter, COMDAT

; 353  :     return S_OK;

	xor	eax, eax

; 354  : }

	ret	12					; 0000000cH
?ExceptionCatcherEnter@CCorProfilerCallbackImpl@@UAGJII@Z ENDP ; CCorProfilerCallbackImpl::ExceptionCatcherEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionUnwindFinallyLeave@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?ExceptionUnwindFinallyLeave@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyLeave, COMDAT

; 347  :     return S_OK;

	xor	eax, eax

; 348  : }

	ret	4
?ExceptionUnwindFinallyLeave@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionUnwindFinallyEnter@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
?ExceptionUnwindFinallyEnter@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyEnter, COMDAT

; 342  :     return S_OK;

	xor	eax, eax

; 343  : }

	ret	8
?ExceptionUnwindFinallyEnter@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ExceptionUnwindFinallyEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionOSHandlerLeave@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
?ExceptionOSHandlerLeave@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ExceptionOSHandlerLeave, COMDAT

; 337  :     return S_OK;

	xor	eax, eax

; 338  : }

	ret	8
?ExceptionOSHandlerLeave@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ExceptionOSHandlerLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionOSHandlerEnter@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
?ExceptionOSHandlerEnter@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ExceptionOSHandlerEnter, COMDAT

; 332  :     return S_OK;

	xor	eax, eax

; 333  : }

	ret	8
?ExceptionOSHandlerEnter@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ExceptionOSHandlerEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionCLRCatcherExecute@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?ExceptionCLRCatcherExecute@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::ExceptionCLRCatcherExecute, COMDAT

; 327  :     return S_OK;

	xor	eax, eax

; 328  : }

	ret	4
?ExceptionCLRCatcherExecute@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionCLRCatcherExecute
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionCLRCatcherFound@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?ExceptionCLRCatcherFound@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::ExceptionCLRCatcherFound, COMDAT

; 322  :     return S_OK;

	xor	eax, eax

; 323  : }

	ret	4
?ExceptionCLRCatcherFound@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionCLRCatcherFound
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionSearchCatcherFound@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
?ExceptionSearchCatcherFound@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ExceptionSearchCatcherFound, COMDAT

; 317  :     return S_OK;

	xor	eax, eax

; 318  : }

	ret	8
?ExceptionSearchCatcherFound@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ExceptionSearchCatcherFound
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionSearchFilterLeave@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?ExceptionSearchFilterLeave@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::ExceptionSearchFilterLeave, COMDAT

; 312  :     return S_OK;

	xor	eax, eax

; 313  : }

	ret	4
?ExceptionSearchFilterLeave@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionSearchFilterLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionSearchFilterEnter@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
?ExceptionSearchFilterEnter@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ExceptionSearchFilterEnter, COMDAT

; 307  :     return S_OK;

	xor	eax, eax

; 308  : }

	ret	8
?ExceptionSearchFilterEnter@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ExceptionSearchFilterEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionSearchFunctionLeave@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?ExceptionSearchFunctionLeave@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::ExceptionSearchFunctionLeave, COMDAT

; 302  :     return S_OK;

	xor	eax, eax

; 303  : }

	ret	4
?ExceptionSearchFunctionLeave@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionSearchFunctionLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionSearchFunctionEnter@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
?ExceptionSearchFunctionEnter@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ExceptionSearchFunctionEnter, COMDAT

; 297  :     return S_OK;

	xor	eax, eax

; 298  : }

	ret	8
?ExceptionSearchFunctionEnter@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ExceptionSearchFunctionEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionUnwindFunctionLeave@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?ExceptionUnwindFunctionLeave@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionLeave, COMDAT

; 292  :     return S_OK;

	xor	eax, eax

; 293  : }

	ret	4
?ExceptionUnwindFunctionLeave@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionLeave
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionUnwindFunctionEnter@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
?ExceptionUnwindFunctionEnter@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionEnter, COMDAT

; 287  :     return S_OK;

	xor	eax, eax

; 288  : }

	ret	8
?ExceptionUnwindFunctionEnter@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ExceptionUnwindFunctionEnter
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ExceptionThrown@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_thrownObjectID$ = 12					; size = 4
?ExceptionThrown@CCorProfilerCallbackImpl@@UAGJI@Z PROC	; CCorProfilerCallbackImpl::ExceptionThrown, COMDAT

; 282  :     return S_OK;

	xor	eax, eax

; 283  : }

	ret	8
?ExceptionThrown@CCorProfilerCallbackImpl@@UAGJI@Z ENDP	; CCorProfilerCallbackImpl::ExceptionThrown
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RootReferences@CCorProfilerCallbackImpl@@UAGJKQAI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_rootRefs$ = 12						; size = 4
_rootRefIDs$ = 16					; size = 4
?RootReferences@CCorProfilerCallbackImpl@@UAGJKQAI@Z PROC ; CCorProfilerCallbackImpl::RootReferences, COMDAT

; 277  :     return S_OK;

	xor	eax, eax

; 278  : }

	ret	12					; 0000000cH
?RootReferences@CCorProfilerCallbackImpl@@UAGJKQAI@Z ENDP ; CCorProfilerCallbackImpl::RootReferences
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ObjectReferences@CCorProfilerCallbackImpl@@UAGJIIKQAI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_objectID$ = 12						; size = 4
_classID$ = 16						; size = 4
_objectRefs$ = 20					; size = 4
_objectRefIDs$ = 24					; size = 4
?ObjectReferences@CCorProfilerCallbackImpl@@UAGJIIKQAI@Z PROC ; CCorProfilerCallbackImpl::ObjectReferences, COMDAT

; 272  :     return S_OK;

	xor	eax, eax

; 273  : }

	ret	20					; 00000014H
?ObjectReferences@CCorProfilerCallbackImpl@@UAGJIIKQAI@Z ENDP ; CCorProfilerCallbackImpl::ObjectReferences
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ObjectsAllocatedByClass@CCorProfilerCallbackImpl@@UAGJKQAIQAK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_classCount$ = 12					; size = 4
_classIDs$ = 16						; size = 4
_objects$ = 20						; size = 4
?ObjectsAllocatedByClass@CCorProfilerCallbackImpl@@UAGJKQAIQAK@Z PROC ; CCorProfilerCallbackImpl::ObjectsAllocatedByClass, COMDAT

; 267  :     return S_OK;

	xor	eax, eax

; 268  : }

	ret	16					; 00000010H
?ObjectsAllocatedByClass@CCorProfilerCallbackImpl@@UAGJKQAIQAK@Z ENDP ; CCorProfilerCallbackImpl::ObjectsAllocatedByClass
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ObjectAllocated@CCorProfilerCallbackImpl@@UAGJII@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_objectID$ = 12						; size = 4
_classID$ = 16						; size = 4
?ObjectAllocated@CCorProfilerCallbackImpl@@UAGJII@Z PROC ; CCorProfilerCallbackImpl::ObjectAllocated, COMDAT

; 262  :     return S_OK;

	xor	eax, eax

; 263  : }

	ret	12					; 0000000cH
?ObjectAllocated@CCorProfilerCallbackImpl@@UAGJII@Z ENDP ; CCorProfilerCallbackImpl::ObjectAllocated
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?MovedReferences@CCorProfilerCallbackImpl@@UAGJKQAI0QAK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_cmovedObjectIDRanges$ = 12				; size = 4
_oldObjectIDRangeStart$ = 16				; size = 4
_newObjectIDRangeStart$ = 20				; size = 4
_cObjectIDRangeLength$ = 24				; size = 4
?MovedReferences@CCorProfilerCallbackImpl@@UAGJKQAI0QAK@Z PROC ; CCorProfilerCallbackImpl::MovedReferences, COMDAT

; 257  :     return S_OK;

	xor	eax, eax

; 258  : }

	ret	20					; 00000014H
?MovedReferences@CCorProfilerCallbackImpl@@UAGJKQAI0QAK@Z ENDP ; CCorProfilerCallbackImpl::MovedReferences
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeThreadResumed@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_threadID$ = 12						; size = 4
?RuntimeThreadResumed@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::RuntimeThreadResumed, COMDAT

; 252  :     return S_OK;

	xor	eax, eax

; 253  : }

	ret	8
?RuntimeThreadResumed@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::RuntimeThreadResumed
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeThreadSuspended@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_threadID$ = 12						; size = 4
?RuntimeThreadSuspended@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::RuntimeThreadSuspended, COMDAT

; 247  :     return S_OK;

	xor	eax, eax

; 248  : }

	ret	8
?RuntimeThreadSuspended@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::RuntimeThreadSuspended
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeResumeFinished@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?RuntimeResumeFinished@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::RuntimeResumeFinished, COMDAT

; 242  :     return S_OK;

	xor	eax, eax

; 243  : }

	ret	4
?RuntimeResumeFinished@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::RuntimeResumeFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeResumeStarted@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?RuntimeResumeStarted@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::RuntimeResumeStarted, COMDAT

; 237  :     return S_OK;

	xor	eax, eax

; 238  : }

	ret	4
?RuntimeResumeStarted@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::RuntimeResumeStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeSuspendAborted@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?RuntimeSuspendAborted@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::RuntimeSuspendAborted, COMDAT

; 232  :     return S_OK;

	xor	eax, eax

; 233  : }

	ret	4
?RuntimeSuspendAborted@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::RuntimeSuspendAborted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeSuspendFinished@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?RuntimeSuspendFinished@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::RuntimeSuspendFinished, COMDAT

; 227  :     return S_OK;

	xor	eax, eax

; 228  : }

	ret	4
?RuntimeSuspendFinished@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::RuntimeSuspendFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RuntimeSuspendStarted@CCorProfilerCallbackImpl@@UAGJW4__MIDL___MIDL_itf_corprof_0000_0006@@@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_suspendReason$ = 12					; size = 4
?RuntimeSuspendStarted@CCorProfilerCallbackImpl@@UAGJW4__MIDL___MIDL_itf_corprof_0000_0006@@@Z PROC ; CCorProfilerCallbackImpl::RuntimeSuspendStarted, COMDAT

; 222  :     return S_OK;

	xor	eax, eax

; 223  : }

	ret	8
?RuntimeSuspendStarted@CCorProfilerCallbackImpl@@UAGJW4__MIDL___MIDL_itf_corprof_0000_0006@@@Z ENDP ; CCorProfilerCallbackImpl::RuntimeSuspendStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingServerSendingReply@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_pCookie$ = 12						; size = 4
_fIsAsync$ = 16						; size = 4
?RemotingServerSendingReply@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z PROC ; CCorProfilerCallbackImpl::RemotingServerSendingReply, COMDAT

; 217  :     return S_OK;

	xor	eax, eax

; 218  : }

	ret	12					; 0000000cH
?RemotingServerSendingReply@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z ENDP ; CCorProfilerCallbackImpl::RemotingServerSendingReply
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingServerInvocationReturned@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?RemotingServerInvocationReturned@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::RemotingServerInvocationReturned, COMDAT

; 212  :     return S_OK;

	xor	eax, eax

; 213  : }

	ret	4
?RemotingServerInvocationReturned@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::RemotingServerInvocationReturned
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingServerInvocationStarted@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?RemotingServerInvocationStarted@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::RemotingServerInvocationStarted, COMDAT

; 207  :     return S_OK;

	xor	eax, eax

; 208  : }

	ret	4
?RemotingServerInvocationStarted@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::RemotingServerInvocationStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingServerReceivingMessage@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_pCookie$ = 12						; size = 4
_fIsAsync$ = 16						; size = 4
?RemotingServerReceivingMessage@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z PROC ; CCorProfilerCallbackImpl::RemotingServerReceivingMessage, COMDAT

; 202  :     return S_OK;

	xor	eax, eax

; 203  : }

	ret	12					; 0000000cH
?RemotingServerReceivingMessage@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z ENDP ; CCorProfilerCallbackImpl::RemotingServerReceivingMessage
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingClientInvocationFinished@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?RemotingClientInvocationFinished@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::RemotingClientInvocationFinished, COMDAT

; 197  : 	return S_OK;

	xor	eax, eax

; 198  : }

	ret	4
?RemotingClientInvocationFinished@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::RemotingClientInvocationFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingClientReceivingReply@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_pCookie$ = 12						; size = 4
_fIsAsync$ = 16						; size = 4
?RemotingClientReceivingReply@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z PROC ; CCorProfilerCallbackImpl::RemotingClientReceivingReply, COMDAT

; 192  :     return S_OK;

	xor	eax, eax

; 193  : }

	ret	12					; 0000000cH
?RemotingClientReceivingReply@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z ENDP ; CCorProfilerCallbackImpl::RemotingClientReceivingReply
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingClientSendingMessage@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_pCookie$ = 12						; size = 4
_fIsAsync$ = 16						; size = 4
?RemotingClientSendingMessage@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z PROC ; CCorProfilerCallbackImpl::RemotingClientSendingMessage, COMDAT

; 187  :     return S_OK;

	xor	eax, eax

; 188  : }

	ret	12					; 0000000cH
?RemotingClientSendingMessage@CCorProfilerCallbackImpl@@UAGJPAU_GUID@@H@Z ENDP ; CCorProfilerCallbackImpl::RemotingClientSendingMessage
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?RemotingClientInvocationStarted@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?RemotingClientInvocationStarted@CCorProfilerCallbackImpl@@UAGJXZ PROC ; CCorProfilerCallbackImpl::RemotingClientInvocationStarted, COMDAT

; 182  :     return S_OK;

	xor	eax, eax

; 183  : }

	ret	4
?RemotingClientInvocationStarted@CCorProfilerCallbackImpl@@UAGJXZ ENDP ; CCorProfilerCallbackImpl::RemotingClientInvocationStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ThreadAssignedToOSThread@CCorProfilerCallbackImpl@@UAGJIK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_managedThreadID$ = 12					; size = 4
_osThreadID$ = 16					; size = 4
?ThreadAssignedToOSThread@CCorProfilerCallbackImpl@@UAGJIK@Z PROC ; CCorProfilerCallbackImpl::ThreadAssignedToOSThread, COMDAT

; 177  :     return S_OK;

	xor	eax, eax

; 178  : }

	ret	12					; 0000000cH
?ThreadAssignedToOSThread@CCorProfilerCallbackImpl@@UAGJIK@Z ENDP ; CCorProfilerCallbackImpl::ThreadAssignedToOSThread
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ThreadDestroyed@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_threadID$ = 12						; size = 4
?ThreadDestroyed@CCorProfilerCallbackImpl@@UAGJI@Z PROC	; CCorProfilerCallbackImpl::ThreadDestroyed, COMDAT

; 172  :     return S_OK;

	xor	eax, eax

; 173  : }

	ret	8
?ThreadDestroyed@CCorProfilerCallbackImpl@@UAGJI@Z ENDP	; CCorProfilerCallbackImpl::ThreadDestroyed
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ThreadCreated@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_threadID$ = 12						; size = 4
?ThreadCreated@CCorProfilerCallbackImpl@@UAGJI@Z PROC	; CCorProfilerCallbackImpl::ThreadCreated, COMDAT

; 167  :     return S_OK;

	xor	eax, eax

; 168  : }

	ret	8
?ThreadCreated@CCorProfilerCallbackImpl@@UAGJI@Z ENDP	; CCorProfilerCallbackImpl::ThreadCreated
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ManagedToUnmanagedTransition@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
_reason$ = 16						; size = 4
?ManagedToUnmanagedTransition@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z PROC ; CCorProfilerCallbackImpl::ManagedToUnmanagedTransition, COMDAT

; 162  :     return S_OK;

	xor	eax, eax

; 163  : }

	ret	12					; 0000000cH
?ManagedToUnmanagedTransition@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z ENDP ; CCorProfilerCallbackImpl::ManagedToUnmanagedTransition
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?UnmanagedToManagedTransition@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
_reason$ = 16						; size = 4
?UnmanagedToManagedTransition@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z PROC ; CCorProfilerCallbackImpl::UnmanagedToManagedTransition, COMDAT

; 157  :     return S_OK;

	xor	eax, eax

; 158  : }

	ret	12					; 0000000cH
?UnmanagedToManagedTransition@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0005@@@Z ENDP ; CCorProfilerCallbackImpl::UnmanagedToManagedTransition
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITInlining@CCorProfilerCallbackImpl@@UAGJIIPAH@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_callerID$ = 12						; size = 4
_calleeID$ = 16						; size = 4
_pfShouldInline$ = 20					; size = 4
?JITInlining@CCorProfilerCallbackImpl@@UAGJIIPAH@Z PROC	; CCorProfilerCallbackImpl::JITInlining, COMDAT

; 152  :     return S_OK;

	xor	eax, eax

; 153  : }

	ret	16					; 00000010H
?JITInlining@CCorProfilerCallbackImpl@@UAGJIIPAH@Z ENDP	; CCorProfilerCallbackImpl::JITInlining
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITFunctionPitched@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
?JITFunctionPitched@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::JITFunctionPitched, COMDAT

; 147  :     return S_OK;

	xor	eax, eax

; 148  : }

	ret	8
?JITFunctionPitched@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::JITFunctionPitched
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITCachedFunctionSearchFinished@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0004@@@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
_result$ = 16						; size = 4
?JITCachedFunctionSearchFinished@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0004@@@Z PROC ; CCorProfilerCallbackImpl::JITCachedFunctionSearchFinished, COMDAT

; 142  :     return S_OK;

	xor	eax, eax

; 143  : }

	ret	12					; 0000000cH
?JITCachedFunctionSearchFinished@CCorProfilerCallbackImpl@@UAGJIW4__MIDL___MIDL_itf_corprof_0000_0004@@@Z ENDP ; CCorProfilerCallbackImpl::JITCachedFunctionSearchFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITCachedFunctionSearchStarted@CCorProfilerCallbackImpl@@UAGJIPAH@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
_pbUseCachedFunction$ = 16				; size = 4
?JITCachedFunctionSearchStarted@CCorProfilerCallbackImpl@@UAGJIPAH@Z PROC ; CCorProfilerCallbackImpl::JITCachedFunctionSearchStarted, COMDAT

; 137  :     return S_OK;

	xor	eax, eax

; 138  : }

	ret	12					; 0000000cH
?JITCachedFunctionSearchStarted@CCorProfilerCallbackImpl@@UAGJIPAH@Z ENDP ; CCorProfilerCallbackImpl::JITCachedFunctionSearchStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITCompilationFinished@CCorProfilerCallbackImpl@@UAGJIJH@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
_hrStatus$ = 16						; size = 4
_fIsSafeToBlock$ = 20					; size = 4
?JITCompilationFinished@CCorProfilerCallbackImpl@@UAGJIJH@Z PROC ; CCorProfilerCallbackImpl::JITCompilationFinished, COMDAT

; 132  :     return S_OK;

	xor	eax, eax

; 133  : }

	ret	16					; 00000010H
?JITCompilationFinished@CCorProfilerCallbackImpl@@UAGJIJH@Z ENDP ; CCorProfilerCallbackImpl::JITCompilationFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?JITCompilationStarted@CCorProfilerCallbackImpl@@UAGJIH@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
_fIsSafeToBlock$ = 16					; size = 4
?JITCompilationStarted@CCorProfilerCallbackImpl@@UAGJIH@Z PROC ; CCorProfilerCallbackImpl::JITCompilationStarted, COMDAT

; 127  :     return S_OK;

	xor	eax, eax

; 128  : }

	ret	12					; 0000000cH
?JITCompilationStarted@CCorProfilerCallbackImpl@@UAGJIH@Z ENDP ; CCorProfilerCallbackImpl::JITCompilationStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?FunctionUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_functionID$ = 12					; size = 4
?FunctionUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::FunctionUnloadStarted, COMDAT

; 122  :     return S_OK;

	xor	eax, eax

; 123  : }

	ret	8
?FunctionUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::FunctionUnloadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ClassUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_classID$ = 12						; size = 4
_hrStatus$ = 16						; size = 4
?ClassUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z PROC ; CCorProfilerCallbackImpl::ClassUnloadFinished, COMDAT

; 117  :     return S_OK;

	xor	eax, eax

; 118  : }

	ret	12					; 0000000cH
?ClassUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ENDP ; CCorProfilerCallbackImpl::ClassUnloadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ClassUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_classID$ = 12						; size = 4
?ClassUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ClassUnloadStarted, COMDAT

; 112  :     return S_OK;

	xor	eax, eax

; 113  : }

	ret	8
?ClassUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ClassUnloadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ClassLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_classID$ = 12						; size = 4
_hrStatus$ = 16						; size = 4
?ClassLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z PROC ; CCorProfilerCallbackImpl::ClassLoadFinished, COMDAT

; 107  :     return S_OK;

	xor	eax, eax

; 108  : }

	ret	12					; 0000000cH
?ClassLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ENDP ; CCorProfilerCallbackImpl::ClassLoadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ClassLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_classID$ = 12						; size = 4
?ClassLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ClassLoadStarted, COMDAT

; 102  :     return S_OK;

	xor	eax, eax

; 103  : }

	ret	8
?ClassLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ClassLoadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ModuleAttachedToAssembly@CCorProfilerCallbackImpl@@UAGJII@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_moduleID$ = 12						; size = 4
_assemblyID$ = 16					; size = 4
?ModuleAttachedToAssembly@CCorProfilerCallbackImpl@@UAGJII@Z PROC ; CCorProfilerCallbackImpl::ModuleAttachedToAssembly, COMDAT

; 97   :     return S_OK;

	xor	eax, eax

; 98   : }

	ret	12					; 0000000cH
?ModuleAttachedToAssembly@CCorProfilerCallbackImpl@@UAGJII@Z ENDP ; CCorProfilerCallbackImpl::ModuleAttachedToAssembly
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ModuleUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_moduleID$ = 12						; size = 4
_hrStatus$ = 16						; size = 4
?ModuleUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z PROC ; CCorProfilerCallbackImpl::ModuleUnloadFinished, COMDAT

; 92   : 	return S_OK;

	xor	eax, eax

; 93   : }

	ret	12					; 0000000cH
?ModuleUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ENDP ; CCorProfilerCallbackImpl::ModuleUnloadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ModuleUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_moduleID$ = 12						; size = 4
?ModuleUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ModuleUnloadStarted, COMDAT

; 87   :     return S_OK;

	xor	eax, eax

; 88   : }

	ret	8
?ModuleUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ModuleUnloadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ModuleLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_moduleID$ = 12						; size = 4
_hrStatus$ = 16						; size = 4
?ModuleLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z PROC ; CCorProfilerCallbackImpl::ModuleLoadFinished, COMDAT

; 82   :     return S_OK;

	xor	eax, eax

; 83   : }

	ret	12					; 0000000cH
?ModuleLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ENDP ; CCorProfilerCallbackImpl::ModuleLoadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ModuleLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_moduleID$ = 12						; size = 4
?ModuleLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::ModuleLoadStarted, COMDAT

; 77   :     return S_OK;

	xor	eax, eax

; 78   : }

	ret	8
?ModuleLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::ModuleLoadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AssemblyUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_assemblyID$ = 12					; size = 4
_hrStatus$ = 16						; size = 4
?AssemblyUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z PROC ; CCorProfilerCallbackImpl::AssemblyUnloadFinished, COMDAT

; 72   :     return S_OK;

	xor	eax, eax

; 73   : }

	ret	12					; 0000000cH
?AssemblyUnloadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ENDP ; CCorProfilerCallbackImpl::AssemblyUnloadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AssemblyUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_assemblyID$ = 12					; size = 4
?AssemblyUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::AssemblyUnloadStarted, COMDAT

; 67   :     return S_OK;

	xor	eax, eax

; 68   : }

	ret	8
?AssemblyUnloadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::AssemblyUnloadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AssemblyLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_assemblyID$ = 12					; size = 4
_hrStatus$ = 16						; size = 4
?AssemblyLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z PROC ; CCorProfilerCallbackImpl::AssemblyLoadFinished, COMDAT

; 62   :     return S_OK;

	xor	eax, eax

; 63   : }

	ret	12					; 0000000cH
?AssemblyLoadFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ENDP ; CCorProfilerCallbackImpl::AssemblyLoadFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AssemblyLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_assemblyID$ = 12					; size = 4
?AssemblyLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::AssemblyLoadStarted, COMDAT

; 57   :     return S_OK;

	xor	eax, eax

; 58   : }

	ret	8
?AssemblyLoadStarted@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::AssemblyLoadStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AppDomainShutdownFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_appDomainID$ = 12					; size = 4
_hrStatus$ = 16						; size = 4
?AppDomainShutdownFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z PROC ; CCorProfilerCallbackImpl::AppDomainShutdownFinished, COMDAT

; 52   :     return S_OK;

	xor	eax, eax

; 53   : }

	ret	12					; 0000000cH
?AppDomainShutdownFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ENDP ; CCorProfilerCallbackImpl::AppDomainShutdownFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AppDomainShutdownStarted@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_appDomainID$ = 12					; size = 4
?AppDomainShutdownStarted@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::AppDomainShutdownStarted, COMDAT

; 47   :     return S_OK;

	xor	eax, eax

; 48   : }

	ret	8
?AppDomainShutdownStarted@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::AppDomainShutdownStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AppDomainCreationFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_appDomainID$ = 12					; size = 4
_hrStatus$ = 16						; size = 4
?AppDomainCreationFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z PROC ; CCorProfilerCallbackImpl::AppDomainCreationFinished, COMDAT

; 42   :     return S_OK;

	xor	eax, eax

; 43   : }

	ret	12					; 0000000cH
?AppDomainCreationFinished@CCorProfilerCallbackImpl@@UAGJIJ@Z ENDP ; CCorProfilerCallbackImpl::AppDomainCreationFinished
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?AppDomainCreationStarted@CCorProfilerCallbackImpl@@UAGJI@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_appDomainID$ = 12					; size = 4
?AppDomainCreationStarted@CCorProfilerCallbackImpl@@UAGJI@Z PROC ; CCorProfilerCallbackImpl::AppDomainCreationStarted, COMDAT

; 37   :     return S_OK;

	xor	eax, eax

; 38   : }

	ret	8
?AppDomainCreationStarted@CCorProfilerCallbackImpl@@UAGJI@Z ENDP ; CCorProfilerCallbackImpl::AppDomainCreationStarted
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?Shutdown@CCorProfilerCallbackImpl@@UAGJXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?Shutdown@CCorProfilerCallbackImpl@@UAGJXZ PROC		; CCorProfilerCallbackImpl::Shutdown, COMDAT

; 32   :     return S_OK;

	xor	eax, eax

; 33   : }

	ret	4
?Shutdown@CCorProfilerCallbackImpl@@UAGJXZ ENDP		; CCorProfilerCallbackImpl::Shutdown
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?Initialize@CCorProfilerCallbackImpl@@UAGJPAUIUnknown@@@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_pICorProfilerInfoUnk$ = 12				; size = 4
?Initialize@CCorProfilerCallbackImpl@@UAGJPAUIUnknown@@@Z PROC ; CCorProfilerCallbackImpl::Initialize, COMDAT

; 27   :     return S_OK;

	xor	eax, eax

; 28   : }

	ret	8
?Initialize@CCorProfilerCallbackImpl@@UAGJPAUIUnknown@@@Z ENDP ; CCorProfilerCallbackImpl::Initialize
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ??0IUnknown@@QAE@XZ
_TEXT	SEGMENT
??0IUnknown@@QAE@XZ PROC				; IUnknown::IUnknown, COMDAT
; _this$ = eax
	ret	0
??0IUnknown@@QAE@XZ ENDP				; IUnknown::IUnknown
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ??0ICorProfilerCallback@@QAE@XZ
_TEXT	SEGMENT
??0ICorProfilerCallback@@QAE@XZ PROC			; ICorProfilerCallback::ICorProfilerCallback, COMDAT
	mov	eax, OFFSET ?profiler@@3VCProfiler@@A	; profiler
	ret	0
??0ICorProfilerCallback@@QAE@XZ ENDP			; ICorProfilerCallback::ICorProfilerCallback
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ??0ICorProfilerCallback2@@QAE@XZ
_TEXT	SEGMENT
??0ICorProfilerCallback2@@QAE@XZ PROC			; ICorProfilerCallback2::ICorProfilerCallback2, COMDAT
	mov	eax, OFFSET ?profiler@@3VCProfiler@@A	; profiler
	ret	0
??0ICorProfilerCallback2@@QAE@XZ ENDP			; ICorProfilerCallback2::ICorProfilerCallback2
_TEXT	ENDS
PUBLIC	??0CCorProfilerCallbackImpl@@QAE@XZ		; CCorProfilerCallbackImpl::CCorProfilerCallbackImpl
; Function compile flags: /Ogtpy
;	COMDAT ??0CCorProfilerCallbackImpl@@QAE@XZ
_TEXT	SEGMENT
??0CCorProfilerCallbackImpl@@QAE@XZ PROC		; CCorProfilerCallbackImpl::CCorProfilerCallbackImpl, COMDAT

; 23   : CCorProfilerCallbackImpl::CCorProfilerCallbackImpl() {}

	mov	DWORD PTR ?profiler@@3VCProfiler@@A, OFFSET ??_7CCorProfilerCallbackImpl@@6B@
	mov	eax, OFFSET ?profiler@@3VCProfiler@@A	; profiler
	ret	0
??0CCorProfilerCallbackImpl@@QAE@XZ ENDP		; CCorProfilerCallbackImpl::CCorProfilerCallbackImpl
END
