; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Local\SharpDevelop_3.2.0.5777_Source\src\AddIns\Misc\Profiler\Hook\EventWaitHandle.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BI@BBOPOAJD@Local?2Profiler?4Event?4?$CFd?$AA@ ; `string'
EXTRN	__imp__OpenEventA@12:PROC
EXTRN	__imp__SetEvent@4:PROC
EXTRN	__imp__ResetEvent@4:PROC
EXTRN	__imp__WaitForSingleObject@8:PROC
EXTRN	??2@YAPAXI@Z:PROC				; operator new
EXTRN	??3@YAXPAX@Z:PROC				; operator delete
EXTRN	__imp__sprintf_s:PROC
EXTRN	??_U@YAPAXI@Z:PROC				; operator new[]
;	COMDAT ??_C@_0BI@BBOPOAJD@Local?2Profiler?4Event?4?$CFd?$AA@
CONST	SEGMENT
??_C@_0BI@BBOPOAJD@Local?2Profiler?4Event?4?$CFd?$AA@ DB 'Local\Profiler.'
	DB	'Event.%d', 00H				; `string'
__bad_alloc_Message DD FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
PUBLIC	?GetEventName@@YAPADH@Z				; GetEventName
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\eventwaithandle.cpp
;	COMDAT ?GetEventName@@YAPADH@Z
_TEXT	SEGMENT
_eventName$ = 8						; size = 4
?GetEventName@@YAPADH@Z PROC				; GetEventName, COMDAT

; 65   : {

	push	esi

; 66   : 	char *evName = new char[128];

	push	128					; 00000080H
	call	??_U@YAPAXI@Z				; operator new[]
	mov	esi, eax

; 67   : 	sprintf_s(evName, 128, "Local\\Profiler.Event.%d", eventName);

	mov	eax, DWORD PTR _eventName$[esp+4]
	push	eax
	push	OFFSET ??_C@_0BI@BBOPOAJD@Local?2Profiler?4Event?4?$CFd?$AA@
	push	128					; 00000080H
	push	esi
	call	DWORD PTR __imp__sprintf_s
	add	esp, 20					; 00000014H

; 68   : 	
; 69   : 	return evName;

	mov	eax, esi
	pop	esi

; 70   : }

	ret	0
?GetEventName@@YAPADH@Z ENDP				; GetEventName
_TEXT	ENDS
PUBLIC	?GetEventHandle@CEventWaitHandle@@QAEPAXXZ	; CEventWaitHandle::GetEventHandle
; Function compile flags: /Ogtpy
;	COMDAT ?GetEventHandle@CEventWaitHandle@@QAEPAXXZ
_TEXT	SEGMENT
?GetEventHandle@CEventWaitHandle@@QAEPAXXZ PROC		; CEventWaitHandle::GetEventHandle, COMDAT
; _this$ = eax

; 47   : 	return this->eventHandle;

	mov	eax, DWORD PTR [eax+4]

; 48   : }

	ret	0
?GetEventHandle@CEventWaitHandle@@QAEPAXXZ ENDP		; CEventWaitHandle::GetEventHandle
_TEXT	ENDS
PUBLIC	?Wait@CEventWaitHandle@@QAEKH@Z			; CEventWaitHandle::Wait
; Function compile flags: /Ogtpy
;	COMDAT ?Wait@CEventWaitHandle@@QAEKH@Z
_TEXT	SEGMENT
?Wait@CEventWaitHandle@@QAEKH@Z PROC			; CEventWaitHandle::Wait, COMDAT
; _this$ = eax

; 36   : 	return WaitForSingleObject(this->eventHandle, milliseconds);

	mov	ecx, DWORD PTR [eax+4]
	push	-1
	push	ecx
	call	DWORD PTR __imp__WaitForSingleObject@8

; 37   : }

	ret	0
?Wait@CEventWaitHandle@@QAEKH@Z ENDP			; CEventWaitHandle::Wait
_TEXT	ENDS
PUBLIC	?Set@CEventWaitHandle@@QAE_NXZ			; CEventWaitHandle::Set
; Function compile flags: /Ogtpy
;	COMDAT ?Set@CEventWaitHandle@@QAE_NXZ
_TEXT	SEGMENT
?Set@CEventWaitHandle@@QAE_NXZ PROC			; CEventWaitHandle::Set, COMDAT
; _this$ = eax

; 24   : 	return SetEvent(this->eventHandle) != 0;

	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	call	DWORD PTR __imp__SetEvent@4
	neg	eax
	sbb	eax, eax
	neg	eax

; 25   : }

	ret	0
?Set@CEventWaitHandle@@QAE_NXZ ENDP			; CEventWaitHandle::Set
_TEXT	ENDS
PUBLIC	??0CEventWaitHandle@@QAE@PAD@Z			; CEventWaitHandle::CEventWaitHandle
; Function compile flags: /Ogtpy
;	COMDAT ??0CEventWaitHandle@@QAE@PAD@Z
_TEXT	SEGMENT
??0CEventWaitHandle@@QAE@PAD@Z PROC			; CEventWaitHandle::CEventWaitHandle, COMDAT
; _this$ = esi
; _name$ = eax

; 17   : 	this->name = name;
; 18   : 	this->eventHandle = OpenEventA(EVENT_MODIFY_STATE | SYNCHRONIZE, false, TEXT(this->name));

	push	eax
	push	0
	push	1048578					; 00100002H
	mov	DWORD PTR [esi], eax
	call	DWORD PTR __imp__OpenEventA@12
	mov	DWORD PTR [esi+4], eax

; 19   : }

	mov	eax, esi
	ret	0
??0CEventWaitHandle@@QAE@PAD@Z ENDP			; CEventWaitHandle::CEventWaitHandle
PUBLIC	?OpenEventWaitHandle@@YAPAVCEventWaitHandle@@PAD@Z ; OpenEventWaitHandle
; Function compile flags: /Ogtpy
;	COMDAT ?OpenEventWaitHandle@@YAPAVCEventWaitHandle@@PAD@Z
_TEXT	SEGMENT
?OpenEventWaitHandle@@YAPAVCEventWaitHandle@@PAD@Z PROC	; OpenEventWaitHandle, COMDAT
; _name$ = edi

; 52   : {

	push	esi

; 53   : 	CEventWaitHandle *handle = new CEventWaitHandle(name);

	push	8
	call	??2@YAPAXI@Z				; operator new
	mov	esi, eax
	add	esp, 4
	test	esi, esi
	je	SHORT $LN4@OpenEventW
	push	edi
	push	0
	push	1048578					; 00100002H
	mov	DWORD PTR [esi], edi
	call	DWORD PTR __imp__OpenEventA@12
	mov	DWORD PTR [esi+4], eax
	mov	eax, esi
	jmp	SHORT $LN5@OpenEventW
$LN4@OpenEventW:
	xor	eax, eax
$LN5@OpenEventW:

; 54   : 
; 55   : 	if (handle->GetEventHandle() == nullptr) {

	cmp	DWORD PTR [eax+4], 0
	pop	esi
	jne	SHORT $LN2@OpenEventW

; 56   : 		delete (void *)handle;

	push	eax
	call	??3@YAXPAX@Z				; operator delete
	add	esp, 4

; 57   : 		return nullptr;

	xor	eax, eax
$LN2@OpenEventW:

; 58   : 	}
; 59   : 
; 60   : 	return handle;
; 61   : }

	ret	0
?OpenEventWaitHandle@@YAPAVCEventWaitHandle@@PAD@Z ENDP	; OpenEventWaitHandle
_TEXT	ENDS
PUBLIC	?Wait@CEventWaitHandle@@QAEKXZ			; CEventWaitHandle::Wait
; Function compile flags: /Ogtpy
;	COMDAT ?Wait@CEventWaitHandle@@QAEKXZ
_TEXT	SEGMENT
?Wait@CEventWaitHandle@@QAEKXZ PROC			; CEventWaitHandle::Wait, COMDAT
; _this$ = eax

; 42   : 	return CEventWaitHandle::Wait(INFINITE);

	mov	ecx, DWORD PTR [eax+4]
	push	-1
	push	ecx
	call	DWORD PTR __imp__WaitForSingleObject@8

; 43   : }

	ret	0
?Wait@CEventWaitHandle@@QAEKXZ ENDP			; CEventWaitHandle::Wait
END
