; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Local\SharpDevelop_3.2.0.5777_Source\src\AddIns\Misc\Profiler\Hook\FunctionInfo.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

__bad_alloc_Message DD FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
PUBLIC	?AddOrUpdateChild@FunctionInfo@@QAEXPAU1@@Z	; FunctionInfo::AddOrUpdateChild
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\functioninfo.cpp
;	COMDAT ?AddOrUpdateChild@FunctionInfo@@QAEXPAU1@@Z
_TEXT	SEGMENT
_child$ = 8						; size = 4
?AddOrUpdateChild@FunctionInfo@@QAEXPAU1@@Z PROC	; FunctionInfo::AddOrUpdateChild, COMDAT
; _this$ = edx

; 29   : {

	push	ebx
	mov	ebx, DWORD PTR _child$[esp]
	push	esi

; 30   : 	int slot = child->Id;
; 31   : 	for (;;) {
; 32   : 		slot &= this->LastChildIndex;

	mov	esi, DWORD PTR [edx+20]
	push	edi
	mov	edi, DWORD PTR [ebx]
	mov	eax, edi
	and	eax, esi

; 33   : 		FunctionInfo *slotContent = this->Children[slot];

	mov	ecx, DWORD PTR [edx+eax*4+24]

; 34   : 		if (slotContent == nullptr || slotContent->Id == child->Id) {

	test	ecx, ecx
	je	SHORT $LN11@AddOrUpdat
$LL4@AddOrUpdat:
	cmp	DWORD PTR [ecx], edi
	je	SHORT $LN11@AddOrUpdat

; 36   : 			break;
; 37   : 		}
; 38   : 		slot++;

	inc	eax
	and	eax, esi
	mov	ecx, DWORD PTR [edx+eax*4+24]
	test	ecx, ecx
	jne	SHORT $LL4@AddOrUpdat
$LN11@AddOrUpdat:
	pop	edi
	pop	esi

; 35   : 			this->Children[slot] = child;

	mov	DWORD PTR [edx+eax*4+24], ebx
	pop	ebx

; 39   : 	}
; 40   : }

	ret	4
?AddOrUpdateChild@FunctionInfo@@QAEXPAU1@@Z ENDP	; FunctionInfo::AddOrUpdateChild
_TEXT	ENDS
PUBLIC	?Check@FunctionInfo@@QAEXXZ			; FunctionInfo::Check
; Function compile flags: /Ogtpy
;	COMDAT ?Check@FunctionInfo@@QAEXXZ
_TEXT	SEGMENT
?Check@FunctionInfo@@QAEXXZ PROC			; FunctionInfo::Check, COMDAT

; 17   : 	#ifdef DEBUG
; 18   : 	int fc = 0;
; 19   : 	for (int i = 0; i <= LastChildIndex; i++) {
; 20   : 		if (Children[i] != nullptr) {
; 21   : 			fc++;
; 22   : 		}
; 23   : 	}
; 24   : 	assert(fc == FillCount);
; 25   : 	#endif
; 26   : }

	ret	0
?Check@FunctionInfo@@QAEXXZ ENDP			; FunctionInfo::Check
PUBLIC	?FreeFunctionInfo@@YAXPAUFunctionInfo@@@Z	; FreeFunctionInfo
; Function compile flags: /Ogtpy
;	COMDAT ?FreeFunctionInfo@@YAXPAUFunctionInfo@@@Z
_TEXT	SEGMENT
?FreeFunctionInfo@@YAXPAUFunctionInfo@@@Z PROC		; FreeFunctionInfo, COMDAT
; _f$ = esi

; 110  : 	sharedMemoryHeader->mallocator.free(f, sizeof(FunctionInfo) + (f->LastChildIndex + 1) * sizeof(FunctionInfo*));

	mov	eax, DWORD PTR [esi+20]
	lea	eax, DWORD PTR [eax*4+28]
	mov	ecx, 374152163				; 164d1be3H
	mul	ecx
	mov	eax, DWORD PTR ?sharedMemoryHeader@@3PAUSharedMemoryHeader@@A ; sharedMemoryHeader
	and	edx, 31					; 0000001fH
	push	ebx
	lea	edx, DWORD PTR [eax+edx*4+64]
	push	edi
	npad	1
$LL5@FreeFuncti:
	mov	ecx, DWORD PTR [edx]
	mov	DWORD PTR [esi], ecx
	mov	edi, esi
	mov	ebx, edx
	mov	eax, ecx
	lock	 cmpxchg DWORD PTR [ebx], edi
	cmp	eax, ecx
	jne	SHORT $LL5@FreeFuncti
	pop	edi
	pop	ebx

; 111  : }

	ret	0
?FreeFunctionInfo@@YAXPAUFunctionInfo@@@Z ENDP		; FreeFunctionInfo
_TEXT	ENDS
PUBLIC	?Resize@FunctionInfo@@AAEPAU1@H@Z		; FunctionInfo::Resize
; Function compile flags: /Ogtpy
;	COMDAT ?Resize@FunctionInfo@@AAEPAU1@H@Z
_TEXT	SEGMENT
_newTableSize$ = 8					; size = 4
?Resize@FunctionInfo@@AAEPAU1@H@Z PROC			; FunctionInfo::Resize, COMDAT
; _this$ = eax

; 58   : {

	push	ebx
	mov	ebx, DWORD PTR _newTableSize$[esp]
	push	esi
	mov	esi, eax

; 59   : //	DebugWriteLine("Resize %d", Id);
; 60   : 	// Allocate space for the copy
; 61   : 	FunctionInfo* newFunction = (FunctionInfo *)sharedMemoryHeader->mallocator.malloc(sizeof(FunctionInfo) + newTableSize * sizeof(void*));

	mov	eax, DWORD PTR ?sharedMemoryHeader@@3PAUSharedMemoryHeader@@A ; sharedMemoryHeader
	push	edi
	add	eax, 52					; 00000034H
	lea	edi, DWORD PTR [ebx*4+24]
	push	eax
	call	?malloc@?$freeListAllocator@UFunctionInfoAllocationSize@@@@QAEPAXI@Z ; freeListAllocator<FunctionInfoAllocationSize>::malloc

; 62   : 
; 63   : 	// Copy the header
; 64   : 	memcpy(newFunction, this, sizeof(FunctionInfo));

	mov	ecx, DWORD PTR [esi]
	mov	DWORD PTR [eax], ecx
	mov	edx, DWORD PTR [esi+4]
	mov	DWORD PTR [eax+4], edx
	mov	ecx, DWORD PTR [esi+8]
	mov	DWORD PTR [eax+8], ecx
	mov	edx, DWORD PTR [esi+12]
	mov	DWORD PTR [eax+12], edx
	mov	ecx, DWORD PTR [esi+16]
	mov	DWORD PTR [eax+16], ecx

; 65   : 	// Initialize the new table
; 66   : 	newFunction->LastChildIndex = newTableSize - 1;

	dec	ebx
	mov	DWORD PTR [eax+20], ebx

; 67   : 	// Copy the old table entries
; 68   : 	int oldTableSize = this->LastChildIndex + 1;

	mov	ecx, DWORD PTR [esi+20]
	inc	ecx

; 69   : 	for(int i = 0; i < oldTableSize; i++) {

	test	ecx, ecx
	jle	SHORT $LN2@Resize
	push	ebp
	lea	ebx, DWORD PTR [esi+24]
	mov	ebp, ecx
	npad	4
$LL19@Resize:

; 70   : 		FunctionInfo *child = this->Children[i];

	mov	edi, DWORD PTR [ebx]

; 71   : 		if (child != nullptr) {

	test	edi, edi
	je	SHORT $LN3@Resize

; 72   : 			newFunction->AddOrUpdateChild(child);

	mov	esi, DWORD PTR [edi]
	mov	ecx, DWORD PTR [eax+20]
	and	ecx, esi
	mov	edx, DWORD PTR [eax+ecx*4+24]
	test	edx, edx
	je	SHORT $LN15@Resize
$LL10@Resize:
	cmp	DWORD PTR [edx], esi
	je	SHORT $LN15@Resize
	inc	ecx
	and	ecx, DWORD PTR [eax+20]
	mov	edx, DWORD PTR [eax+ecx*4+24]
	test	edx, edx
	jne	SHORT $LL10@Resize
$LN15@Resize:
	mov	DWORD PTR [eax+ecx*4+24], edi
$LN3@Resize:

; 69   : 	for(int i = 0; i < oldTableSize; i++) {

	add	ebx, 4
	sub	ebp, 1
	jne	SHORT $LL19@Resize
	pop	ebp
$LN2@Resize:
	pop	edi
	pop	esi
	pop	ebx

; 73   : 		}
; 74   : 	}
; 75   : 	// we cannot delete the original yet - we need to wait until all pointers to it have been updated,
; 76   : 	// because updating a pointer is safely possible only while the original still exists!
; 77   : 	// Done - FunctionInfo was resized
; 78   : 	return newFunction;
; 79   : }

	ret	4
?Resize@FunctionInfo@@AAEPAU1@H@Z ENDP			; FunctionInfo::Resize
_TEXT	ENDS
PUBLIC	?CreateFunctionInfo@@YAPAUFunctionInfo@@HH@Z	; CreateFunctionInfo
; Function compile flags: /Ogtpy
;	COMDAT ?CreateFunctionInfo@@YAPAUFunctionInfo@@HH@Z
_TEXT	SEGMENT
_id$ = 8						; size = 4
_indexInParent$ = 12					; size = 4
?CreateFunctionInfo@@YAPAUFunctionInfo@@HH@Z PROC	; CreateFunctionInfo, COMDAT

; 44   : 	// Allocate the child in memory
; 45   : 	FunctionInfo* newFunction = (FunctionInfo *)sharedMemoryHeader->mallocator.malloc(sizeof(FunctionInfo) + defaultTableSize * sizeof(void*));

	mov	eax, DWORD PTR ?sharedMemoryHeader@@3PAUSharedMemoryHeader@@A ; sharedMemoryHeader
	push	edi
	add	eax, 52					; 00000034H
	push	eax
	mov	edi, 40					; 00000028H
	call	?malloc@?$freeListAllocator@UFunctionInfoAllocationSize@@@@QAEPAXI@Z ; freeListAllocator<FunctionInfoAllocationSize>::malloc

; 46   : 	// the allocater takes care of zeroing the memory
; 47   : 	
; 48   : 	// Set field values
; 49   : 	newFunction->Id = id;

	mov	edx, DWORD PTR _id$[esp]
	mov	ecx, eax

; 50   : 	newFunction->TimeSpent = (ULONGLONG)indexInParent << 56;

	mov	eax, DWORD PTR _indexInParent$[esp]
	mov	DWORD PTR [ecx], edx
	cdq
	shl	eax, 24					; 00000018H
	mov	DWORD PTR [ecx+12], eax
	mov	DWORD PTR [ecx+8], 0

; 51   : 	// Initialize the table
; 52   : 	newFunction->LastChildIndex = defaultTableSize - 1;

	mov	DWORD PTR [ecx+20], 3

; 53   : 	// Return pointer to the created child
; 54   : 	return newFunction;

	mov	eax, ecx
	pop	edi

; 55   : }

	ret	0
?CreateFunctionInfo@@YAPAUFunctionInfo@@HH@Z ENDP	; CreateFunctionInfo
PUBLIC	?GetOrAddChild@FunctionInfo@@QAEPAU1@HAAPAU1@@Z	; FunctionInfo::GetOrAddChild
; Function compile flags: /Ogtpy
;	COMDAT ?GetOrAddChild@FunctionInfo@@QAEPAU1@HAAPAU1@@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
tv181 = 12						; size = 4
_functionID$ = 12					; size = 4
_newParent$ = 16					; size = 4
?GetOrAddChild@FunctionInfo@@QAEPAU1@HAAPAU1@@Z PROC	; FunctionInfo::GetOrAddChild, COMDAT

; 82   : {

	push	ebx
	mov	ebx, DWORD PTR _this$[esp]

; 83   : 	int lastChildIndex = this->LastChildIndex;

	mov	ecx, DWORD PTR [ebx+20]
	push	ebp
	mov	ebp, DWORD PTR _functionID$[esp+4]
	push	esi

; 84   : 	int slot = functionID;
; 85   : 	for (;;) {
; 86   : 		slot &= lastChildIndex;

	mov	esi, ecx
	and	esi, ebp

; 87   : 		FunctionInfo *slotContent = this->Children[slot];

	mov	eax, DWORD PTR [ebx+esi*4+24]

; 88   : 		if (slotContent == nullptr) {

	test	eax, eax
	je	SHORT $LN18@GetOrAddCh
	npad	6
$LL7@GetOrAddCh:

; 101  : 		} else if (slotContent->Id == functionID) {

	cmp	DWORD PTR [eax], ebp
	je	$LN6@GetOrAddCh

; 102  : 			return slotContent;
; 103  : 		}
; 104  : 		slot++;

	inc	esi
	and	esi, ecx
	mov	eax, DWORD PTR [ebx+esi*4+24]
	test	eax, eax
	jne	SHORT $LL7@GetOrAddCh
$LN18@GetOrAddCh:

; 89   : 			this->FillCount++;

	inc	DWORD PTR [ebx+16]
	mov	eax, DWORD PTR [ebx+16]
	mov	DWORD PTR tv181[esp+8], eax

; 90   : 			if (this->FillCount * 4 >= lastChildIndex * 3) {

	add	eax, eax
	add	eax, eax
	lea	edx, DWORD PTR [ecx+ecx*2]
	cmp	eax, edx
	push	edi
	jl	SHORT $LN4@GetOrAddCh

; 91   : 				// resize table
; 92   : 				newParent = this->Resize(2 * (lastChildIndex + 1));

	lea	eax, DWORD PTR [ecx+ecx+2]
	push	eax
	mov	eax, ebx
	call	?Resize@FunctionInfo@@AAEPAU1@H@Z	; FunctionInfo::Resize

; 93   : 				slotContent = CreateFunctionInfo(functionID, newParent->FillCount);

	mov	ecx, DWORD PTR ?sharedMemoryHeader@@3PAUSharedMemoryHeader@@A ; sharedMemoryHeader
	mov	ebx, DWORD PTR _newParent$[esp+12]
	mov	esi, DWORD PTR [eax+16]
	add	ecx, 52					; 00000034H
	push	ecx
	mov	edi, 40					; 00000028H
	mov	DWORD PTR [ebx], eax
	call	?malloc@?$freeListAllocator@UFunctionInfoAllocationSize@@@@QAEPAXI@Z ; freeListAllocator<FunctionInfoAllocationSize>::malloc
	mov	ecx, eax
	mov	eax, esi
	cdq

; 94   : 				newParent->AddOrUpdateChild(slotContent);

	mov	edx, DWORD PTR [ebx]
	shl	eax, 24					; 00000018H
	push	ecx
	mov	DWORD PTR [ecx], ebp
	mov	DWORD PTR [ecx+8], 0
	mov	DWORD PTR [ecx+12], eax
	mov	DWORD PTR [ecx+20], 3
	mov	edi, ecx
	call	?AddOrUpdateChild@FunctionInfo@@QAEXPAU1@@Z ; FunctionInfo::AddOrUpdateChild

; 98   : 				this->Children[slot] = slotContent;
; 99   : 			}
; 100  : 			return slotContent;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx

; 105  : 	}
; 106  : }

	ret	12					; 0000000cH
$LN4@GetOrAddCh:

; 95   : 				newParent->Check();
; 96   : 			} else {
; 97   : 				slotContent = CreateFunctionInfo(functionID, this->FillCount);

	mov	edx, DWORD PTR ?sharedMemoryHeader@@3PAUSharedMemoryHeader@@A ; sharedMemoryHeader
	add	edx, 52					; 00000034H
	push	edx
	mov	edi, 40					; 00000028H
	call	?malloc@?$freeListAllocator@UFunctionInfoAllocationSize@@@@QAEPAXI@Z ; freeListAllocator<FunctionInfoAllocationSize>::malloc
	mov	ecx, eax
	mov	eax, DWORD PTR tv181[esp+12]
	cdq
	shl	eax, 24					; 00000018H
	mov	edi, ecx
	mov	DWORD PTR [ecx+12], eax
	mov	DWORD PTR [ecx], ebp
	mov	DWORD PTR [ecx+8], 0
	mov	DWORD PTR [ecx+20], 3

; 98   : 				this->Children[slot] = slotContent;
; 99   : 			}
; 100  : 			return slotContent;

	mov	eax, edi
	mov	DWORD PTR [ebx+esi*4+24], ecx
	pop	edi
$LN6@GetOrAddCh:
	pop	esi
	pop	ebp
	pop	ebx

; 105  : 	}
; 106  : }

	ret	12					; 0000000cH
?GetOrAddChild@FunctionInfo@@QAEPAU1@HAAPAU1@@Z ENDP	; FunctionInfo::GetOrAddChild
END
