; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Local\SharpDevelop_3.2.0.5777_Source\src\AddIns\Misc\Profiler\Hook\LightweightList.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??2@YAPAXIPAX@Z					; operator new
PUBLIC	??3@YAXPAX0@Z					; operator delete
PUBLIC	??1?$LightweightStack@UStackEntry@@@@QAE@XZ	; LightweightStack<StackEntry>::~LightweightStack<StackEntry>
PUBLIC	??1ThreadLocalData@@QAE@XZ			; ThreadLocalData::~ThreadLocalData
PUBLIC	??_GThreadLocalData@@QAEPAXI@Z			; ThreadLocalData::`scalar deleting destructor'
EXTRN	__imp__ReleaseMutex@4:PROC
__bad_alloc_Message DD FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
PUBLIC	??0LightweightList@@QAE@PAX@Z			; LightweightList::LightweightList
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\lightweightlist.cpp
;	COMDAT ??0LightweightList@@QAE@PAX@Z
_TEXT	SEGMENT
??0LightweightList@@QAE@PAX@Z PROC			; LightweightList::LightweightList, COMDAT
; _this$ = eax
; _mutex$ = ecx

; 15   : 	this->lastItem = nullptr;

	mov	DWORD PTR [eax], 0

; 16   : 	this->mutex = mutex;

	mov	DWORD PTR [eax+4], ecx

; 17   : }

	ret	0
??0LightweightList@@QAE@PAX@Z ENDP			; LightweightList::LightweightList
; Function compile flags: /Ogtpy
; File c:\program files\microsoft visual studio 9.0\vc\include\new
_TEXT	ENDS
;	COMDAT ??3@YAXPAX0@Z
_TEXT	SEGMENT
??3@YAXPAX0@Z PROC					; operator delete, COMDAT

; 64   : 	}

	ret	0
??3@YAXPAX0@Z ENDP					; operator delete
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ??2@YAPAXIPAX@Z
_TEXT	SEGMENT
??2@YAPAXIPAX@Z PROC					; operator new, COMDAT
; __Where$ = eax

; 59   : 	return (_Where);
; 60   : 	}

	ret	0
??2@YAPAXIPAX@Z ENDP					; operator new
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\lightweightstack.h
;	COMDAT ??1?$LightweightStack@UStackEntry@@@@QAE@XZ
_TEXT	SEGMENT
??1?$LightweightStack@UStackEntry@@@@QAE@XZ PROC	; LightweightStack<StackEntry>::~LightweightStack<StackEntry>, COMDAT

; 43   : 		stackAllocator.free(array, (arrayEnd - array) * sizeof(T));
; 44   : 	}

	ret	0
??1?$LightweightStack@UStackEntry@@@@QAE@XZ ENDP	; LightweightStack<StackEntry>::~LightweightStack<StackEntry>
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ??1ThreadLocalData@@QAE@XZ
_TEXT	SEGMENT
??1ThreadLocalData@@QAE@XZ PROC				; ThreadLocalData::~ThreadLocalData, COMDAT
	ret	0
??1ThreadLocalData@@QAE@XZ ENDP				; ThreadLocalData::~ThreadLocalData
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ??_GThreadLocalData@@QAEPAXI@Z
_TEXT	SEGMENT
??_GThreadLocalData@@QAEPAXI@Z PROC			; ThreadLocalData::`scalar deleting destructor', COMDAT
; _this$ = eax
	ret	0
??_GThreadLocalData@@QAEPAXI@Z ENDP			; ThreadLocalData::`scalar deleting destructor'
_TEXT	ENDS
PUBLIC	?remove@LightweightList@@QAEXPAUThreadLocalData@@@Z ; LightweightList::remove
; Function compile flags: /Ogtpy
; File c:\local\sharpdevelop_3.2.0.5777_source\src\addins\misc\profiler\hook\lightweightlist.cpp
;	COMDAT ?remove@LightweightList@@QAEXPAUThreadLocalData@@@Z
_TEXT	SEGMENT
?remove@LightweightList@@QAEXPAUThreadLocalData@@@Z PROC ; LightweightList::remove, COMDAT
; _item$ = edi

; 46   : {

	push	esi
	mov	esi, DWORD PTR ?allThreadLocalDatas@@3PAVLightweightList@@A ; allThreadLocalDatas

; 47   : 	WaitForSingleObject(this->mutex, INFINITE);

	mov	eax, DWORD PTR [esi+4]
	push	-1
	push	eax
	call	DWORD PTR __imp__WaitForSingleObject@8

; 48   : 
; 49   : 	assert(item != nullptr);
; 50   : 	assert(this->lastItem != nullptr);
; 51   : 
; 52   : 	if (item == this->lastItem) {

	mov	eax, DWORD PTR [esi]
	cmp	edi, eax
	jne	SHORT $LN4@remove

; 53   : 		this->lastItem = this->lastItem->predecessor;

	mov	eax, DWORD PTR [eax+8]
	mov	DWORD PTR [esi], eax

; 54   : 		if (this->lastItem != nullptr)

	test	eax, eax
	je	SHORT $LN1@remove

; 55   : 			this->lastItem->follower = nullptr;

	mov	DWORD PTR [eax+12], 0

; 56   : 	} else {

	jmp	SHORT $LN1@remove
$LN4@remove:

; 57   : 		item->follower->predecessor = item->predecessor;

	mov	ecx, DWORD PTR [edi+12]
	mov	edx, DWORD PTR [edi+8]
	mov	DWORD PTR [ecx+8], edx

; 58   : 		if (item->predecessor != nullptr)

	mov	eax, DWORD PTR [edi+8]
	test	eax, eax
	je	SHORT $LN1@remove

; 59   : 			item->predecessor->follower = item->follower;

	mov	ecx, DWORD PTR [edi+12]
	mov	DWORD PTR [eax+12], ecx
$LN1@remove:

; 60   : 	}
; 61   : 
; 62   : 	item->~ThreadLocalData();
; 63   : 
; 64   : 	stackAllocator.free(item, sizeof(ThreadLocalData));
; 65   : 
; 66   : 	sharedMemoryHeader->LastThreadListItem = this->lastItem;

	mov	edx, DWORD PTR [esi]
	mov	eax, DWORD PTR ?sharedMemoryHeader@@3PAUSharedMemoryHeader@@A ; sharedMemoryHeader
	mov	DWORD PTR [eax+40], edx

; 67   : 
; 68   : 	ReleaseMutex(this->mutex);

	mov	ecx, DWORD PTR [esi+4]
	push	ecx
	call	DWORD PTR __imp__ReleaseMutex@4
	pop	esi

; 69   : }

	ret	0
?remove@LightweightList@@QAEXPAUThreadLocalData@@@Z ENDP ; LightweightList::remove
PUBLIC	?add@LightweightList@@QAEPAUThreadLocalData@@XZ	; LightweightList::add
; Function compile flags: /Ogtpy
;	COMDAT ?add@LightweightList@@QAEPAUThreadLocalData@@XZ
_TEXT	SEGMENT
?add@LightweightList@@QAEPAUThreadLocalData@@XZ PROC	; LightweightList::add, COMDAT

; 20   : {

	push	esi
	push	edi
	mov	edi, DWORD PTR ?allThreadLocalDatas@@3PAVLightweightList@@A ; allThreadLocalDatas

; 21   : 	WaitForSingleObject(this->mutex, INFINITE);

	mov	eax, DWORD PTR [edi+4]
	push	-1
	push	eax
	call	DWORD PTR __imp__WaitForSingleObject@8

; 22   : 
; 23   : 	void *itemMemory = stackAllocator.malloc(sizeof(ThreadLocalData));

	mov	esi, 28					; 0000001cH
	mov	ecx, OFFSET ?stackAllocator@@3UfastAllocator@@A+4
	lock	 xadd	 DWORD PTR [ecx], esi
	mov	edx, DWORD PTR ?stackAllocator@@3UfastAllocator@@A+8
	sub	edx, esi
	cmp	edx, 28					; 0000001cH

; 24   : 	assert(itemMemory != nullptr);
; 25   : 	ThreadLocalData *item = new (itemMemory) ThreadLocalData();

	jle	SHORT $LN5@add
	test	esi, esi
	je	SHORT $LN5@add
	mov	eax, 1536				; 00000600H
	lock	 xadd	 DWORD PTR [ecx], eax
	mov	edx, DWORD PTR ?stackAllocator@@3UfastAllocator@@A+8
	sub	edx, eax
	xor	ecx, ecx
	cmp	edx, 1536				; 00000600H
	setle	cl
	dec	ecx
	and	eax, ecx
	lea	edx, DWORD PTR [eax+1536]
	mov	DWORD PTR [esi+16], eax
	add	eax, -24				; ffffffe8H
	mov	DWORD PTR [esi+24], edx
	mov	DWORD PTR [esi+20], eax
	call	DWORD PTR __imp__GetCurrentThreadId@0
	mov	DWORD PTR [esi], eax
	jmp	SHORT $LN6@add
$LN5@add:
	xor	esi, esi
$LN6@add:

; 26   : 
; 27   : 	if (this->lastItem == nullptr) {

	mov	eax, DWORD PTR [edi]
	test	eax, eax
	jne	SHORT $LN2@add

; 28   : 		this->lastItem = item;

	mov	DWORD PTR [edi], esi

; 29   : 		this->lastItem->follower = nullptr;

	mov	DWORD PTR [esi+12], eax

; 30   : 		this->lastItem->predecessor = nullptr;

	mov	eax, DWORD PTR [edi]
	mov	DWORD PTR [eax+8], 0

; 31   : 	} else {

	jmp	SHORT $LN1@add
$LN2@add:

; 32   : 		this->lastItem->follower = item;

	mov	DWORD PTR [eax+12], esi

; 33   : 		item->follower = nullptr;

	mov	DWORD PTR [esi+12], 0

; 34   : 		item->predecessor = this->lastItem;

	mov	ecx, DWORD PTR [edi]
	mov	DWORD PTR [esi+8], ecx

; 35   : 		this->lastItem = item;

	mov	DWORD PTR [edi], esi
$LN1@add:

; 36   : 	}
; 37   : 
; 38   : 	sharedMemoryHeader->LastThreadListItem = this->lastItem;

	mov	edx, DWORD PTR [edi]
	mov	eax, DWORD PTR ?sharedMemoryHeader@@3PAUSharedMemoryHeader@@A ; sharedMemoryHeader
	mov	DWORD PTR [eax+40], edx

; 39   : 
; 40   : 	ReleaseMutex(this->mutex);

	mov	ecx, DWORD PTR [edi+4]
	push	ecx
	call	DWORD PTR __imp__ReleaseMutex@4
	pop	edi

; 41   : 
; 42   : 	return item;

	mov	eax, esi
	pop	esi

; 43   : }

	ret	0
?add@LightweightList@@QAEPAUThreadLocalData@@XZ ENDP	; LightweightList::add
END
